# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/scenario/scenario_enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"morai/scenario/scenario_enum.proto\x12\x16morai_sim_api.scenario*\x89\x01\n\x0eSpawnPointType\x12 \n\x1cSPAWN_POINT_TYPE_UNSPECIFIED\x10\x00\x12(\n$SPAWN_POINT_TYPE_VEHICLE_SPAWN_POINT\x10\x01\x12+\n\'SPAWN_POINT_TYPE_PEDESTRIAN_SPAWN_POINT\x10\x02*\x98\x02\n\x12PedestrianBehavior\x12#\n\x1fPEDESTRIAN_BEHAVIOR_UNSPECIFIED\x10\x00\x12\x1c\n\x18PEDESTRIAN_BEHAVIOR_ONCE\x10\x01\x12#\n\x1fPEDESTRIAN_BEHAVIOR_CLOSED_LOOP\x10\x02\x12\x1e\n\x1aPEDESTRIAN_BEHAVIOR_REPEAT\x10\x03\x12\x1c\n\x18PEDESTRIAN_BEHAVIOR_LOOP\x10\x04\x12 \n\x1cPEDESTRIAN_BEHAVIOR_NEW_PATH\x10\x05\x12\x1d\n\x19PEDESTRIAN_BEHAVIOR_STAND\x10\x06\x12\x1b\n\x17PEDESTRIAN_BEHAVIOR_END\x10\x07*o\n\nLengthType\x12\x14\n\x10LENGTH_TYPE_MINI\x10\x00\x12\x17\n\x13LENGTH_TYPE_COMPACT\x10\x01\x12\x1b\n\x17LENGTH_TYPE_MIDDLE_SIZE\x10\x02\x12\x15\n\x11LENGTH_TYPE_LARGE\x10\x03*i\n\x0bLatBiasMode\x12\x18\n\x14LAT_BIAS_UNSPECIFIED\x10\x00\x12\x10\n\x0cLAT_BIAS_FIX\x10\x01\x12\x1c\n\x18LAT_BIAS_RANDOM_GAUSSIAN\x10\x02\x12\x10\n\x0cLAT_BIAS_END\x10\x03*\x86\x01\n\x0cVelocityType\x12\x1d\n\x19VELOCITY_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aVELOCITY_TYPE_LINKVELOCITY\x10\x01\x12 \n\x1cVELOCITY_TYPE_CUSTOMVELOCITY\x10\x02\x12\x15\n\x11VELOCITY_TYPE_END\x10\x03*\xb4\x01\n\x10\x44rivingParamType\x12*\n&VEHICLE_DRIVING_PARAM_TYPE_UNSPECIFIED\x10\x00\x12\'\n#VEHICLE_DRIVING_PARAM_TYPE_CONSTANT\x10\x01\x12\'\n#VEHICLE_DRIVING_PARAM_TYPE_VARIABLE\x10\x02\x12\"\n\x1eVEHICLE_DRIVING_PARAM_TYPE_END\x10\x03\x42/H\x01\xaa\x02*CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenariob\x06proto3')

_SPAWNPOINTTYPE = DESCRIPTOR.enum_types_by_name['SpawnPointType']
SpawnPointType = enum_type_wrapper.EnumTypeWrapper(_SPAWNPOINTTYPE)
_PEDESTRIANBEHAVIOR = DESCRIPTOR.enum_types_by_name['PedestrianBehavior']
PedestrianBehavior = enum_type_wrapper.EnumTypeWrapper(_PEDESTRIANBEHAVIOR)
_LENGTHTYPE = DESCRIPTOR.enum_types_by_name['LengthType']
LengthType = enum_type_wrapper.EnumTypeWrapper(_LENGTHTYPE)
_LATBIASMODE = DESCRIPTOR.enum_types_by_name['LatBiasMode']
LatBiasMode = enum_type_wrapper.EnumTypeWrapper(_LATBIASMODE)
_VELOCITYTYPE = DESCRIPTOR.enum_types_by_name['VelocityType']
VelocityType = enum_type_wrapper.EnumTypeWrapper(_VELOCITYTYPE)
_DRIVINGPARAMTYPE = DESCRIPTOR.enum_types_by_name['DrivingParamType']
DrivingParamType = enum_type_wrapper.EnumTypeWrapper(_DRIVINGPARAMTYPE)
SPAWN_POINT_TYPE_UNSPECIFIED = 0
SPAWN_POINT_TYPE_VEHICLE_SPAWN_POINT = 1
SPAWN_POINT_TYPE_PEDESTRIAN_SPAWN_POINT = 2
PEDESTRIAN_BEHAVIOR_UNSPECIFIED = 0
PEDESTRIAN_BEHAVIOR_ONCE = 1
PEDESTRIAN_BEHAVIOR_CLOSED_LOOP = 2
PEDESTRIAN_BEHAVIOR_REPEAT = 3
PEDESTRIAN_BEHAVIOR_LOOP = 4
PEDESTRIAN_BEHAVIOR_NEW_PATH = 5
PEDESTRIAN_BEHAVIOR_STAND = 6
PEDESTRIAN_BEHAVIOR_END = 7
LENGTH_TYPE_MINI = 0
LENGTH_TYPE_COMPACT = 1
LENGTH_TYPE_MIDDLE_SIZE = 2
LENGTH_TYPE_LARGE = 3
LAT_BIAS_UNSPECIFIED = 0
LAT_BIAS_FIX = 1
LAT_BIAS_RANDOM_GAUSSIAN = 2
LAT_BIAS_END = 3
VELOCITY_TYPE_UNSPECIFIED = 0
VELOCITY_TYPE_LINKVELOCITY = 1
VELOCITY_TYPE_CUSTOMVELOCITY = 2
VELOCITY_TYPE_END = 3
VEHICLE_DRIVING_PARAM_TYPE_UNSPECIFIED = 0
VEHICLE_DRIVING_PARAM_TYPE_CONSTANT = 1
VEHICLE_DRIVING_PARAM_TYPE_VARIABLE = 2
VEHICLE_DRIVING_PARAM_TYPE_END = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002*CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario'
  _SPAWNPOINTTYPE._serialized_start=63
  _SPAWNPOINTTYPE._serialized_end=200
  _PEDESTRIANBEHAVIOR._serialized_start=203
  _PEDESTRIANBEHAVIOR._serialized_end=483
  _LENGTHTYPE._serialized_start=485
  _LENGTHTYPE._serialized_end=596
  _LATBIASMODE._serialized_start=598
  _LATBIASMODE._serialized_end=703
  _VELOCITYTYPE._serialized_start=706
  _VELOCITYTYPE._serialized_end=840
  _DRIVINGPARAMTYPE._serialized_start=843
  _DRIVINGPARAMTYPE._serialized_end=1023
# @@protoc_insertion_point(module_scope)
