# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/scenario/scenario_object.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$morai/scenario/scenario_object.proto\x12\x16morai_sim_api.scenario\x1a\x17morai/common/type.proto\x1a\x1emorai/common/object_info.proto\"\xea\x01\n\x1e\x43reateFrictionControlAreaParam\x12.\n\x0bobject_info\x18\x01 \x01(\x0b\x32\x19.morai_sim_api.ObjectInfo\x12+\n\ttransform\x18\x02 \x01(\x0b\x32\x18.morai_sim_api.Transform\x12\x13\n\x0bobject_name\x18\x03 \x01(\t\x12\x17\n\x0fvertical_radius\x18\x04 \x01(\x02\x12\x19\n\x11horizontal_radius\x18\x05 \x01(\x02\x12\x0e\n\x06height\x18\x06 \x01(\x02\x12\x12\n\nmultiplier\x18\x07 \x01(\x02\x42/H\x01\xaa\x02*CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenariob\x06proto3')



_CREATEFRICTIONCONTROLAREAPARAM = DESCRIPTOR.message_types_by_name['CreateFrictionControlAreaParam']
CreateFrictionControlAreaParam = _reflection.GeneratedProtocolMessageType('CreateFrictionControlAreaParam', (_message.Message,), {
  'DESCRIPTOR' : _CREATEFRICTIONCONTROLAREAPARAM,
  '__module__' : 'morai.scenario.scenario_object_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.scenario.CreateFrictionControlAreaParam)
  })
_sym_db.RegisterMessage(CreateFrictionControlAreaParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002*CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario'
  _CREATEFRICTIONCONTROLAREAPARAM._serialized_start=122
  _CREATEFRICTIONCONTROLAREAPARAM._serialized_end=356
# @@protoc_insertion_point(module_scope)
