# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/scenario/scenario.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.scenario import spawn_point_pb2 as morai_dot_scenario_dot_spawn__point__pb2
from morai.scenario import scenario_object_pb2 as morai_dot_scenario_dot_scenario__object__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmorai/scenario/scenario.proto\x12\x16morai_sim_api.scenario\x1a\x17morai/common/type.proto\x1a\x19morai/common/result.proto\x1a morai/scenario/spawn_point.proto\x1a$morai/scenario/scenario_object.proto2\xee\x03\n\x08Scenario\x12\x46\n\x11LoadMoraiScenario\x12\x1a.morai_sim_api.StringValue\x1a\x15.morai_sim_api.Result\x12\x66\n\x17\x43reateVehicleSpawnPoint\x12\x34.morai_sim_api.scenario.CreateVehicleSpawnPointParam\x1a\x15.morai_sim_api.Result\x12l\n\x1a\x43reatePedestrianSpawnPoint\x12\x37.morai_sim_api.scenario.CreatePedestrianSpawnPointParam\x1a\x15.morai_sim_api.Result\x12X\n\x10\x45nableSpawnPoint\x12-.morai_sim_api.scenario.EnableSpawnPointParam\x1a\x15.morai_sim_api.Result\x12j\n\x19\x43reateFrictionControlArea\x12\x36.morai_sim_api.scenario.CreateFrictionControlAreaParam\x1a\x15.morai_sim_api.ResultB/H\x01\xaa\x02*CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenariob\x06proto3')



_SCENARIO = DESCRIPTOR.services_by_name['Scenario']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002*CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario'
  _SCENARIO._serialized_start=182
  _SCENARIO._serialized_end=676
# @@protoc_insertion_point(module_scope)
