# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.scenario import scenario_object_pb2 as morai_dot_scenario_dot_scenario__object__pb2
from morai.scenario import spawn_point_pb2 as morai_dot_scenario_dot_spawn__point__pb2


class ScenarioStub(object):
    """*
    시나리오 관련 기능을 제공하는 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadMoraiScenario = channel.unary_unary(
                '/morai_sim_api.scenario.Scenario/LoadMoraiScenario',
                request_serializer=morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.CreateVehicleSpawnPoint = channel.unary_unary(
                '/morai_sim_api.scenario.Scenario/CreateVehicleSpawnPoint',
                request_serializer=morai_dot_scenario_dot_spawn__point__pb2.CreateVehicleSpawnPointParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.CreatePedestrianSpawnPoint = channel.unary_unary(
                '/morai_sim_api.scenario.Scenario/CreatePedestrianSpawnPoint',
                request_serializer=morai_dot_scenario_dot_spawn__point__pb2.CreatePedestrianSpawnPointParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.EnableSpawnPoint = channel.unary_unary(
                '/morai_sim_api.scenario.Scenario/EnableSpawnPoint',
                request_serializer=morai_dot_scenario_dot_spawn__point__pb2.EnableSpawnPointParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.CreateFrictionControlArea = channel.unary_unary(
                '/morai_sim_api.scenario.Scenario/CreateFrictionControlArea',
                request_serializer=morai_dot_scenario_dot_scenario__object__pb2.CreateFrictionControlAreaParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )


class ScenarioServicer(object):
    """*
    시나리오 관련 기능을 제공하는 서비스
    """

    def LoadMoraiScenario(self, request, context):
        """MORAI SIM: Drive의 Built-in 시나리오 파일 로드
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVehicleSpawnPoint(self, request, context):
        """Vehicle Spawn Point 생성
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePedestrianSpawnPoint(self, request, context):
        """Pedestrian Spawn Point 생성
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableSpawnPoint(self, request, context):
        """Spawn Point Enable/Disable
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFrictionControlArea(self, request, context):
        """시나리오 객체 생성
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScenarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadMoraiScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadMoraiScenario,
                    request_deserializer=morai_dot_common_dot_type__pb2.StringValue.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'CreateVehicleSpawnPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVehicleSpawnPoint,
                    request_deserializer=morai_dot_scenario_dot_spawn__point__pb2.CreateVehicleSpawnPointParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'CreatePedestrianSpawnPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePedestrianSpawnPoint,
                    request_deserializer=morai_dot_scenario_dot_spawn__point__pb2.CreatePedestrianSpawnPointParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'EnableSpawnPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableSpawnPoint,
                    request_deserializer=morai_dot_scenario_dot_spawn__point__pb2.EnableSpawnPointParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'CreateFrictionControlArea': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFrictionControlArea,
                    request_deserializer=morai_dot_scenario_dot_scenario__object__pb2.CreateFrictionControlAreaParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.scenario.Scenario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scenario(object):
    """*
    시나리오 관련 기능을 제공하는 서비스
    """

    @staticmethod
    def LoadMoraiScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.scenario.Scenario/LoadMoraiScenario',
            morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateVehicleSpawnPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.scenario.Scenario/CreateVehicleSpawnPoint',
            morai_dot_scenario_dot_spawn__point__pb2.CreateVehicleSpawnPointParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePedestrianSpawnPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.scenario.Scenario/CreatePedestrianSpawnPoint',
            morai_dot_scenario_dot_spawn__point__pb2.CreatePedestrianSpawnPointParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableSpawnPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.scenario.Scenario/EnableSpawnPoint',
            morai_dot_scenario_dot_spawn__point__pb2.EnableSpawnPointParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateFrictionControlArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.scenario.Scenario/CreateFrictionControlArea',
            morai_dot_scenario_dot_scenario__object__pb2.CreateFrictionControlAreaParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
