# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/simulator/available_object.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&morai/simulator/available_object.proto\x12\x17morai_sim_api.simualtor\"\x8f\x01\n\x0f\x41vailableObject\x12\x13\n\x0b\x65go_vehicle\x18\x01 \x03(\t\x12\x18\n\x10surround_vehicle\x18\x02 \x03(\t\x12\x12\n\npedestrian\x18\x03 \x03(\t\x12\x10\n\x08obstacle\x18\x04 \x03(\t\x12\x13\n\x0bspawn_point\x18\x05 \x03(\t\x12\x12\n\nmap_object\x18\x06 \x03(\tB0H\x01\xaa\x02+CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulatorb\x06proto3')



_AVAILABLEOBJECT = DESCRIPTOR.message_types_by_name['AvailableObject']
AvailableObject = _reflection.GeneratedProtocolMessageType('AvailableObject', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLEOBJECT,
  '__module__' : 'morai.simulator.available_object_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simualtor.AvailableObject)
  })
_sym_db.RegisterMessage(AvailableObject)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002+CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulator'
  _AVAILABLEOBJECT._serialized_start=68
  _AVAILABLEOBJECT._serialized_end=211
# @@protoc_insertion_point(module_scope)
