# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/simulator/category_obstacles.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(morai/simulator/category_obstacles.proto\x12\x17morai_sim_api.simualtor\"s\n\x11\x43\x61tegoryObstacles\x12\x0f\n\x07vehicle\x18\x01 \x01(\x08\x12\x12\n\npedestrian\x18\x02 \x01(\x08\x12\x10\n\x08obstacle\x18\x03 \x01(\x08\x12\x13\n\x0bspawn_point\x18\x04 \x01(\x08\x12\x12\n\nmap_object\x18\x05 \x01(\x08\x42\x30H\x01\xaa\x02+CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulatorb\x06proto3')



_CATEGORYOBSTACLES = DESCRIPTOR.message_types_by_name['CategoryObstacles']
CategoryObstacles = _reflection.GeneratedProtocolMessageType('CategoryObstacles', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYOBSTACLES,
  '__module__' : 'morai.simulator.category_obstacles_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simualtor.CategoryObstacles)
  })
_sym_db.RegisterMessage(CategoryObstacles)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002+CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulator'
  _CATEGORYOBSTACLES._serialized_start=69
  _CATEGORYOBSTACLES._serialized_end=184
# @@protoc_insertion_point(module_scope)
