# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/simulator/rendering.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmorai/simulator/rendering.proto\x12\x17morai_sim_api.simualtor\"R\n\rRenderingMode\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\x31\n\x04size\x18\x02 \x01(\x0b\x32#.morai_sim_api.simualtor.WindowSize\"+\n\nWindowSize\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x42\x30H\x01\xaa\x02+CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulatorb\x06proto3')



_RENDERINGMODE = DESCRIPTOR.message_types_by_name['RenderingMode']
_WINDOWSIZE = DESCRIPTOR.message_types_by_name['WindowSize']
RenderingMode = _reflection.GeneratedProtocolMessageType('RenderingMode', (_message.Message,), {
  'DESCRIPTOR' : _RENDERINGMODE,
  '__module__' : 'morai.simulator.rendering_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simualtor.RenderingMode)
  })
_sym_db.RegisterMessage(RenderingMode)

WindowSize = _reflection.GeneratedProtocolMessageType('WindowSize', (_message.Message,), {
  'DESCRIPTOR' : _WINDOWSIZE,
  '__module__' : 'morai.simulator.rendering_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simualtor.WindowSize)
  })
_sym_db.RegisterMessage(WindowSize)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002+CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulator'
  _RENDERINGMODE._serialized_start=60
  _RENDERINGMODE._serialized_end=142
  _WINDOWSIZE._serialized_start=144
  _WINDOWSIZE._serialized_end=187
# @@protoc_insertion_point(module_scope)
