# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/simulator/simulator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.simulator import available_object_pb2 as morai_dot_simulator_dot_available__object__pb2
from morai.simulator import category_obstacles_pb2 as morai_dot_simulator_dot_category__obstacles__pb2
from morai.simulator import rendering_pb2 as morai_dot_simulator_dot_rendering__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmorai/simulator/simulator.proto\x12\x17morai_sim_api.simualtor\x1a\x17morai/common/type.proto\x1a\x19morai/common/result.proto\x1a&morai/simulator/available_object.proto\x1a(morai/simulator/category_obstacles.proto\x1a\x1fmorai/simulator/rendering.proto2\x96\x04\n\tSimulator\x12G\n\x13GetSimulatorVersion\x12\x14.morai_sim_api.Empty\x1a\x1a.morai_sim_api.StringValue\x12?\n\x0cGetTimestamp\x12\x14.morai_sim_api.Empty\x1a\x19.morai_sim_api.Int64Value\x12\x43\n\x10GetAvailableMaps\x12\x14.morai_sim_api.Empty\x1a\x19.morai_sim_api.StringList\x12j\n\x12GetAvailableObject\x12*.morai_sim_api.simualtor.CategoryObstacles\x1a(.morai_sim_api.simualtor.AvailableObject\x12?\n\x0bGetDataPath\x12\x14.morai_sim_api.Empty\x1a\x1a.morai_sim_api.StringValue\x12Q\n\x10SetRenderingMode\x12&.morai_sim_api.simualtor.RenderingMode\x1a\x15.morai_sim_api.Result\x12:\n\x0c\x43heckLatency\x12\x14.morai_sim_api.Empty\x1a\x14.morai_sim_api.EmptyB0H\x01\xaa\x02+CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulatorb\x06proto3')



_SIMULATOR = DESCRIPTOR.services_by_name['Simulator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002+CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulator'
  _SIMULATOR._serialized_start=228
  _SIMULATOR._serialized_end=762
# @@protoc_insertion_point(module_scope)
