# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.simulator import available_object_pb2 as morai_dot_simulator_dot_available__object__pb2
from morai.simulator import category_obstacles_pb2 as morai_dot_simulator_dot_category__obstacles__pb2
from morai.simulator import rendering_pb2 as morai_dot_simulator_dot_rendering__pb2


class SimulatorStub(object):
    """*
    MORAI SIM의 정보 확인을 위한 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSimulatorVersion = channel.unary_unary(
                '/morai_sim_api.simualtor.Simulator/GetSimulatorVersion',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.StringValue.FromString,
                )
        self.GetTimestamp = channel.unary_unary(
                '/morai_sim_api.simualtor.Simulator/GetTimestamp',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.Int64Value.FromString,
                )
        self.GetAvailableMaps = channel.unary_unary(
                '/morai_sim_api.simualtor.Simulator/GetAvailableMaps',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.StringList.FromString,
                )
        self.GetAvailableObject = channel.unary_unary(
                '/morai_sim_api.simualtor.Simulator/GetAvailableObject',
                request_serializer=morai_dot_simulator_dot_category__obstacles__pb2.CategoryObstacles.SerializeToString,
                response_deserializer=morai_dot_simulator_dot_available__object__pb2.AvailableObject.FromString,
                )
        self.GetDataPath = channel.unary_unary(
                '/morai_sim_api.simualtor.Simulator/GetDataPath',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.StringValue.FromString,
                )
        self.SetRenderingMode = channel.unary_unary(
                '/morai_sim_api.simualtor.Simulator/SetRenderingMode',
                request_serializer=morai_dot_simulator_dot_rendering__pb2.RenderingMode.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.CheckLatency = channel.unary_unary(
                '/morai_sim_api.simualtor.Simulator/CheckLatency',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                )


class SimulatorServicer(object):
    """*
    MORAI SIM의 정보 확인을 위한 서비스
    """

    def GetSimulatorVersion(self, request, context):
        """시뮬레이터 버전 확인
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimestamp(self, request, context):
        """시뮬레이터의 Timestamp 확인
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableMaps(self, request, context):
        """현재 사용자가 사용 가능한 맵 리스트 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableObject(self, request, context):
        """Get Available Object matched to the user account info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataPath(self, request, context):
        """데이터 저장 경로 획득
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRenderingMode(self, request, context):
        """랜더링 모드 변경
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckLatency(self, request, context):
        """latency check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSimulatorVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulatorVersion,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
            ),
            'GetTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimestamp,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.Int64Value.SerializeToString,
            ),
            'GetAvailableMaps': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableMaps,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.StringList.SerializeToString,
            ),
            'GetAvailableObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableObject,
                    request_deserializer=morai_dot_simulator_dot_category__obstacles__pb2.CategoryObstacles.FromString,
                    response_serializer=morai_dot_simulator_dot_available__object__pb2.AvailableObject.SerializeToString,
            ),
            'GetDataPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataPath,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
            ),
            'SetRenderingMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRenderingMode,
                    request_deserializer=morai_dot_simulator_dot_rendering__pb2.RenderingMode.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'CheckLatency': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLatency,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.simualtor.Simulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulator(object):
    """*
    MORAI SIM의 정보 확인을 위한 서비스
    """

    @staticmethod
    def GetSimulatorVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simualtor.Simulator/GetSimulatorVersion',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_type__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simualtor.Simulator/GetTimestamp',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_type__pb2.Int64Value.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableMaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simualtor.Simulator/GetAvailableMaps',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_type__pb2.StringList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simualtor.Simulator/GetAvailableObject',
            morai_dot_simulator_dot_category__obstacles__pb2.CategoryObstacles.SerializeToString,
            morai_dot_simulator_dot_available__object__pb2.AvailableObject.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simualtor.Simulator/GetDataPath',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_type__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRenderingMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simualtor.Simulator/SetRenderingMode',
            morai_dot_simulator_dot_rendering__pb2.RenderingMode.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckLatency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simualtor.Simulator/CheckLatency',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_type__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
