# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/util/raycast.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18morai/util/raycast.proto\x12\x12morai_sim_api.util\x1a\x17morai/common/type.proto\"p\n\x0cRaycastParam\x12&\n\x06source\x18\x01 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12&\n\x06target\x18\x02 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12\x10\n\x08max_dist\x18\x03 \x01(\x02\x42+H\x01\xaa\x02&CoreLib.Grpc.Protobuf.MoraiSimAPI.Utilb\x06proto3')



_RAYCASTPARAM = DESCRIPTOR.message_types_by_name['RaycastParam']
RaycastParam = _reflection.GeneratedProtocolMessageType('RaycastParam', (_message.Message,), {
  'DESCRIPTOR' : _RAYCASTPARAM,
  '__module__' : 'morai.util.raycast_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.util.RaycastParam)
  })
_sym_db.RegisterMessage(RaycastParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002&CoreLib.Grpc.Protobuf.MoraiSimAPI.Util'
  _RAYCASTPARAM._serialized_start=73
  _RAYCASTPARAM._serialized_end=185
# @@protoc_insertion_point(module_scope)
