# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/util/util.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.util import raycast_pb2 as morai_dot_util_dot_raycast__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15morai/util/util.proto\x12\x12morai_sim_api.util\x1a\x17morai/common/type.proto\x1a\x18morai/util/raycast.proto2N\n\x04Util\x12\x46\n\x07RayCast\x12 .morai_sim_api.util.RaycastParam\x1a\x19.morai_sim_api.FloatValueB+H\x01\xaa\x02&CoreLib.Grpc.Protobuf.MoraiSimAPI.Utilb\x06proto3')



_UTIL = DESCRIPTOR.services_by_name['Util']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002&CoreLib.Grpc.Protobuf.MoraiSimAPI.Util'
  _UTIL._serialized_start=96
  _UTIL._serialized_end=174
# @@protoc_insertion_point(module_scope)
