# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.util import raycast_pb2 as morai_dot_util_dot_raycast__pb2


class UtilStub(object):
    """시뮬레이션 시 사용하는 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RayCast = channel.unary_unary(
                '/morai_sim_api.util.Util/RayCast',
                request_serializer=morai_dot_util_dot_raycast__pb2.RaycastParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.FloatValue.FromString,
                )


class UtilServicer(object):
    """시뮬레이션 시 사용하는 서비스
    """

    def RayCast(self, request, context):
        """Raycast
        response : hit distance (meter). if failed, return -1
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UtilServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RayCast': grpc.unary_unary_rpc_method_handler(
                    servicer.RayCast,
                    request_deserializer=morai_dot_util_dot_raycast__pb2.RaycastParam.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.FloatValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.util.Util', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Util(object):
    """시뮬레이션 시 사용하는 서비스
    """

    @staticmethod
    def RayCast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.util.Util/RayCast',
            morai_dot_util_dot_raycast__pb2.RaycastParam.SerializeToString,
            morai_dot_common_dot_type__pb2.FloatValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
