# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/environment/env_visibility.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.environment import environment_enum_pb2 as morai_dot_environment_dot_environment__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&morai/environment/env_visibility.proto\x12\x19morai_sim_api.environment\x1a(morai/environment/environment_enum.proto\"_\n\rEnvVisibility\x12:\n\x04type\x18\x01 \x01(\x0e\x32,.morai_sim_api.environment.EnvVisibilityType\x12\x12\n\nis_visible\x18\x02 \x01(\x08\x42\x32H\x01\xaa\x02-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environmentb\x06proto3')



_ENVVISIBILITY = DESCRIPTOR.message_types_by_name['EnvVisibility']
EnvVisibility = _reflection.GeneratedProtocolMessageType('EnvVisibility', (_message.Message,), {
  'DESCRIPTOR' : _ENVVISIBILITY,
  '__module__' : 'morai.environment.env_visibility_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.environment.EnvVisibility)
  })
_sym_db.RegisterMessage(EnvVisibility)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment'
  _ENVVISIBILITY._serialized_start=111
  _ENVVISIBILITY._serialized_end=206
# @@protoc_insertion_point(module_scope)
