# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/environment/environment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.environment import weather_pb2 as morai_dot_environment_dot_weather__pb2
from morai.environment import season_pb2 as morai_dot_environment_dot_season__pb2
from morai.environment import time_pb2 as morai_dot_environment_dot_time__pb2
from morai.environment import env_visibility_pb2 as morai_dot_environment_dot_env__visibility__pb2
from morai.environment import force_pb2 as morai_dot_environment_dot_force__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#morai/environment/environment.proto\x12\x19morai_sim_api.environment\x1a\x17morai/common/type.proto\x1a\x19morai/common/result.proto\x1a\x1fmorai/environment/weather.proto\x1a\x1emorai/environment/season.proto\x1a\x1cmorai/environment/time.proto\x1a&morai/environment/env_visibility.proto\x1a\x1dmorai/environment/force.proto2\xf4\x05\n\x0b\x45nvironment\x12J\n\x07GetTime\x12\x14.morai_sim_api.Empty\x1a).morai_sim_api.environment.SimulationTime\x12K\n\x07SetTime\x12).morai_sim_api.environment.SimulationTime\x1a\x15.morai_sim_api.Result\x12\x46\n\nGetWeather\x12\x14.morai_sim_api.Empty\x1a\".morai_sim_api.environment.Weather\x12G\n\nSetWeather\x12\".morai_sim_api.environment.Weather\x1a\x15.morai_sim_api.Result\x12\x44\n\tGetSeason\x12\x14.morai_sim_api.Empty\x1a!.morai_sim_api.environment.Season\x12\x45\n\tSetSeason\x12!.morai_sim_api.environment.Season\x1a\x15.morai_sim_api.Result\x12\x42\n\x0fGetRoadFriction\x12\x14.morai_sim_api.Empty\x1a\x19.morai_sim_api.FloatValue\x12\x43\n\x0fSetRoadFriction\x12\x19.morai_sim_api.FloatValue\x1a\x15.morai_sim_api.Result\x12P\n\rSetVisibility\x12(.morai_sim_api.environment.EnvVisibility\x1a\x15.morai_sim_api.Result\x12S\n\x10SetExternalForce\x12(.morai_sim_api.environment.ExternalForce\x1a\x15.morai_sim_api.ResultB2H\x01\xaa\x02-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environmentb\x06proto3')



_ENVIRONMENT = DESCRIPTOR.services_by_name['Environment']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment'
  _ENVIRONMENT._serialized_start=285
  _ENVIRONMENT._serialized_end=1041
# @@protoc_insertion_point(module_scope)
