# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/environment/environment_enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(morai/environment/environment_enum.proto\x12\x19morai_sim_api.environment*\x9e\x01\n\x0bWeatherType\x12\x16\n\x12WEATHER_TYPE_SUNNY\x10\x00\x12\x17\n\x13WEATHER_TYPE_CLOUDY\x10\x01\x12\x16\n\x12WEATHER_TYPE_FOGGY\x10\x02\x12\x16\n\x12WEATHER_TYPE_STORM\x10\x03\x12\x16\n\x12WEATHER_TYPE_RAINY\x10\x04\x12\x16\n\x12WEATHER_TYPE_SNOWY\x10\x05*j\n\nSeasonType\x12\x16\n\x12SEASON_TYPE_WINTER\x10\x00\x12\x16\n\x12SEASON_TYPE_SPRING\x10\x01\x12\x16\n\x12SEASON_TYPE_SUMMER\x10\x02\x12\x14\n\x10SEASON_TYPE_FALL\x10\x03*3\n\x11\x45nvVisibilityType\x12\x1e\n\x1a\x45NV_VISIBILITY_TYPE_PUDDLE\x10\x00\x42\x32H\x01\xaa\x02-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environmentb\x06proto3')

_WEATHERTYPE = DESCRIPTOR.enum_types_by_name['WeatherType']
WeatherType = enum_type_wrapper.EnumTypeWrapper(_WEATHERTYPE)
_SEASONTYPE = DESCRIPTOR.enum_types_by_name['SeasonType']
SeasonType = enum_type_wrapper.EnumTypeWrapper(_SEASONTYPE)
_ENVVISIBILITYTYPE = DESCRIPTOR.enum_types_by_name['EnvVisibilityType']
EnvVisibilityType = enum_type_wrapper.EnumTypeWrapper(_ENVVISIBILITYTYPE)
WEATHER_TYPE_SUNNY = 0
WEATHER_TYPE_CLOUDY = 1
WEATHER_TYPE_FOGGY = 2
WEATHER_TYPE_STORM = 3
WEATHER_TYPE_RAINY = 4
WEATHER_TYPE_SNOWY = 5
SEASON_TYPE_WINTER = 0
SEASON_TYPE_SPRING = 1
SEASON_TYPE_SUMMER = 2
SEASON_TYPE_FALL = 3
ENV_VISIBILITY_TYPE_PUDDLE = 0


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment'
  _WEATHERTYPE._serialized_start=72
  _WEATHERTYPE._serialized_end=230
  _SEASONTYPE._serialized_start=232
  _SEASONTYPE._serialized_end=338
  _ENVVISIBILITYTYPE._serialized_start=340
  _ENVVISIBILITYTYPE._serialized_end=391
# @@protoc_insertion_point(module_scope)
