# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.environment import env_visibility_pb2 as morai_dot_environment_dot_env__visibility__pb2
from morai.environment import force_pb2 as morai_dot_environment_dot_force__pb2
from morai.environment import season_pb2 as morai_dot_environment_dot_season__pb2
from morai.environment import time_pb2 as morai_dot_environment_dot_time__pb2
from morai.environment import weather_pb2 as morai_dot_environment_dot_weather__pb2


class EnvironmentStub(object):
    """*
    시뮬레이션 환경 관련 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/morai_sim_api.environment.Environment/GetTime',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_environment_dot_time__pb2.SimulationTime.FromString,
                )
        self.SetTime = channel.unary_unary(
                '/morai_sim_api.environment.Environment/SetTime',
                request_serializer=morai_dot_environment_dot_time__pb2.SimulationTime.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetWeather = channel.unary_unary(
                '/morai_sim_api.environment.Environment/GetWeather',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_environment_dot_weather__pb2.Weather.FromString,
                )
        self.SetWeather = channel.unary_unary(
                '/morai_sim_api.environment.Environment/SetWeather',
                request_serializer=morai_dot_environment_dot_weather__pb2.Weather.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetSeason = channel.unary_unary(
                '/morai_sim_api.environment.Environment/GetSeason',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_environment_dot_season__pb2.Season.FromString,
                )
        self.SetSeason = channel.unary_unary(
                '/morai_sim_api.environment.Environment/SetSeason',
                request_serializer=morai_dot_environment_dot_season__pb2.Season.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetRoadFriction = channel.unary_unary(
                '/morai_sim_api.environment.Environment/GetRoadFriction',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.FloatValue.FromString,
                )
        self.SetRoadFriction = channel.unary_unary(
                '/morai_sim_api.environment.Environment/SetRoadFriction',
                request_serializer=morai_dot_common_dot_type__pb2.FloatValue.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVisibility = channel.unary_unary(
                '/morai_sim_api.environment.Environment/SetVisibility',
                request_serializer=morai_dot_environment_dot_env__visibility__pb2.EnvVisibility.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetExternalForce = channel.unary_unary(
                '/morai_sim_api.environment.Environment/SetExternalForce',
                request_serializer=morai_dot_environment_dot_force__pb2.ExternalForce.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )


class EnvironmentServicer(object):
    """*
    시뮬레이션 환경 관련 서비스
    """

    def GetTime(self, request, context):
        """*
        시뮬레이션 시간 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTime(self, request, context):
        """*
        시뮬레이션 시간 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeather(self, request, context):
        """*
        날씨 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWeather(self, request, context):
        """*
        날씨 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeason(self, request, context):
        """*
        계절 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSeason(self, request, context):
        """*
        계절 변경
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoadFriction(self, request, context):
        """*
        도로면 마찰 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRoadFriction(self, request, context):
        """*
        도로면 마찰 변경
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVisibility(self, request, context):
        """*
        맵 환경 요소 가시화
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExternalForce(self, request, context):
        """*
        물체에 외력 주입
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_environment_dot_time__pb2.SimulationTime.SerializeToString,
            ),
            'SetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTime,
                    request_deserializer=morai_dot_environment_dot_time__pb2.SimulationTime.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeather,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_environment_dot_weather__pb2.Weather.SerializeToString,
            ),
            'SetWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWeather,
                    request_deserializer=morai_dot_environment_dot_weather__pb2.Weather.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetSeason': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeason,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_environment_dot_season__pb2.Season.SerializeToString,
            ),
            'SetSeason': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSeason,
                    request_deserializer=morai_dot_environment_dot_season__pb2.Season.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetRoadFriction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoadFriction,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.FloatValue.SerializeToString,
            ),
            'SetRoadFriction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRoadFriction,
                    request_deserializer=morai_dot_common_dot_type__pb2.FloatValue.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVisibility': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVisibility,
                    request_deserializer=morai_dot_environment_dot_env__visibility__pb2.EnvVisibility.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetExternalForce': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExternalForce,
                    request_deserializer=morai_dot_environment_dot_force__pb2.ExternalForce.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.environment.Environment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Environment(object):
    """*
    시뮬레이션 환경 관련 서비스
    """

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/GetTime',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_environment_dot_time__pb2.SimulationTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/SetTime',
            morai_dot_environment_dot_time__pb2.SimulationTime.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/GetWeather',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_environment_dot_weather__pb2.Weather.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/SetWeather',
            morai_dot_environment_dot_weather__pb2.Weather.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSeason(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/GetSeason',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_environment_dot_season__pb2.Season.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSeason(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/SetSeason',
            morai_dot_environment_dot_season__pb2.Season.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoadFriction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/GetRoadFriction',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_type__pb2.FloatValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRoadFriction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/SetRoadFriction',
            morai_dot_common_dot_type__pb2.FloatValue.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVisibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/SetVisibility',
            morai_dot_environment_dot_env__visibility__pb2.EnvVisibility.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetExternalForce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.environment.Environment/SetExternalForce',
            morai_dot_environment_dot_force__pb2.ExternalForce.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
