# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/environment/force.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmorai/environment/force.proto\x12\x19morai_sim_api.environment\x1a\x17morai/common/type.proto\x1a\x1emorai/common/object_info.proto\"\xd0\x01\n\rExternalForce\x12.\n\x0btarget_info\x18\x01 \x01(\x0b\x32\x19.morai_sim_api.ObjectInfo\x12(\n\x08position\x18\x02 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12%\n\x05\x66orce\x18\x03 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12\x15\n\ractive_period\x18\x04 \x01(\x01\x12\x13\n\x0brest_period\x18\x05 \x01(\x01\x12\x12\n\nrepetition\x18\x06 \x01(\rB2H\x01\xaa\x02-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environmentb\x06proto3')



_EXTERNALFORCE = DESCRIPTOR.message_types_by_name['ExternalForce']
ExternalForce = _reflection.GeneratedProtocolMessageType('ExternalForce', (_message.Message,), {
  'DESCRIPTOR' : _EXTERNALFORCE,
  '__module__' : 'morai.environment.force_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.environment.ExternalForce)
  })
_sym_db.RegisterMessage(ExternalForce)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment'
  _EXTERNALFORCE._serialized_start=118
  _EXTERNALFORCE._serialized_end=326
# @@protoc_insertion_point(module_scope)
