# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/environment/season.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.environment import environment_enum_pb2 as morai_dot_environment_dot_environment__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emorai/environment/season.proto\x12\x19morai_sim_api.environment\x1a(morai/environment/environment_enum.proto\"=\n\x06Season\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.morai_sim_api.environment.SeasonTypeB2H\x01\xaa\x02-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environmentb\x06proto3')



_SEASON = DESCRIPTOR.message_types_by_name['Season']
Season = _reflection.GeneratedProtocolMessageType('Season', (_message.Message,), {
  'DESCRIPTOR' : _SEASON,
  '__module__' : 'morai.environment.season_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.environment.Season)
  })
_sym_db.RegisterMessage(Season)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment'
  _SEASON._serialized_start=103
  _SEASON._serialized_end=164
# @@protoc_insertion_point(module_scope)
