# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/environment/time.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmorai/environment/time.proto\x12\x19morai_sim_api.environment\"D\n\x0eSimulationTime\x12\x0c\n\x04hour\x18\x01 \x01(\x05\x12\x11\n\tdata_only\x18\x02 \x01(\x08\x12\x11\n\tinstantly\x18\x03 \x01(\x08\x42\x32H\x01\xaa\x02-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environmentb\x06proto3')



_SIMULATIONTIME = DESCRIPTOR.message_types_by_name['SimulationTime']
SimulationTime = _reflection.GeneratedProtocolMessageType('SimulationTime', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONTIME,
  '__module__' : 'morai.environment.time_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.environment.SimulationTime)
  })
_sym_db.RegisterMessage(SimulationTime)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment'
  _SIMULATIONTIME._serialized_start=59
  _SIMULATIONTIME._serialized_end=127
# @@protoc_insertion_point(module_scope)
