# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/environment/weather.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.environment import environment_enum_pb2 as morai_dot_environment_dot_environment__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmorai/environment/weather.proto\x12\x19morai_sim_api.environment\x1a(morai/environment/environment_enum.proto\"R\n\x07Weather\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.morai_sim_api.environment.WeatherType\x12\x11\n\tinstantly\x18\x02 \x01(\x08\x42\x32H\x01\xaa\x02-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environmentb\x06proto3')



_WEATHER = DESCRIPTOR.message_types_by_name['Weather']
Weather = _reflection.GeneratedProtocolMessageType('Weather', (_message.Message,), {
  'DESCRIPTOR' : _WEATHER,
  '__module__' : 'morai.environment.weather_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.environment.Weather)
  })
_sym_db.RegisterMessage(Weather)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002-CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment'
  _WEATHER._serialized_start=104
  _WEATHER._serialized_end=186
# @@protoc_insertion_point(module_scope)
