# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/simulation/resim.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.simulation import simulation_enum_pb2 as morai_dot_simulation_dot_simulation__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmorai/simulation/resim.proto\x12\x18morai_sim_api.simulation\x1a&morai/simulation/simulation_enum.proto\"w\n\x10ResimRecordParam\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.morai_sim_api.simulation.ResimRecordStatusType\x12\x10\n\x08interval\x18\x02 \x01(\x05\x12\x10\n\x08\x66ilepath\x18\x03 \x01(\t\"Y\n\x16ResimRecordStatusParam\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.morai_sim_api.simulation.ResimRecordStatusType\"\x93\x01\n\x14ResimReplayInitParam\x12\x14\n\x0cweather_list\x18\x01 \x03(\t\x12\x11\n\ttime_list\x18\x02 \x03(\x03\x12\x1a\n\x12scenario_file_path\x18\x03 \x01(\t\x12\x17\n\x0fresim_file_Path\x18\x04 \x01(\t\x12\x1d\n\x15save_sensor_file_path\x18\x05 \x01(\t\"3\n\x15ResimReplayRangeParam\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"9\n\x10ResimReplayParam\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x13\n\x0b\x66rame_range\x18\x02 \x01(\t\"v\n\x16ResimReplayStatusParam\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\x05\x12\x46\n\rreplay_status\x18\x02 \x01(\x0e\x32/.morai_sim_api.simulation.ResimReplayStatusTypeB1H\x01\xaa\x02,CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulationb\x06proto3')



_RESIMRECORDPARAM = DESCRIPTOR.message_types_by_name['ResimRecordParam']
_RESIMRECORDSTATUSPARAM = DESCRIPTOR.message_types_by_name['ResimRecordStatusParam']
_RESIMREPLAYINITPARAM = DESCRIPTOR.message_types_by_name['ResimReplayInitParam']
_RESIMREPLAYRANGEPARAM = DESCRIPTOR.message_types_by_name['ResimReplayRangeParam']
_RESIMREPLAYPARAM = DESCRIPTOR.message_types_by_name['ResimReplayParam']
_RESIMREPLAYSTATUSPARAM = DESCRIPTOR.message_types_by_name['ResimReplayStatusParam']
ResimRecordParam = _reflection.GeneratedProtocolMessageType('ResimRecordParam', (_message.Message,), {
  'DESCRIPTOR' : _RESIMRECORDPARAM,
  '__module__' : 'morai.simulation.resim_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.ResimRecordParam)
  })
_sym_db.RegisterMessage(ResimRecordParam)

ResimRecordStatusParam = _reflection.GeneratedProtocolMessageType('ResimRecordStatusParam', (_message.Message,), {
  'DESCRIPTOR' : _RESIMRECORDSTATUSPARAM,
  '__module__' : 'morai.simulation.resim_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.ResimRecordStatusParam)
  })
_sym_db.RegisterMessage(ResimRecordStatusParam)

ResimReplayInitParam = _reflection.GeneratedProtocolMessageType('ResimReplayInitParam', (_message.Message,), {
  'DESCRIPTOR' : _RESIMREPLAYINITPARAM,
  '__module__' : 'morai.simulation.resim_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.ResimReplayInitParam)
  })
_sym_db.RegisterMessage(ResimReplayInitParam)

ResimReplayRangeParam = _reflection.GeneratedProtocolMessageType('ResimReplayRangeParam', (_message.Message,), {
  'DESCRIPTOR' : _RESIMREPLAYRANGEPARAM,
  '__module__' : 'morai.simulation.resim_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.ResimReplayRangeParam)
  })
_sym_db.RegisterMessage(ResimReplayRangeParam)

ResimReplayParam = _reflection.GeneratedProtocolMessageType('ResimReplayParam', (_message.Message,), {
  'DESCRIPTOR' : _RESIMREPLAYPARAM,
  '__module__' : 'morai.simulation.resim_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.ResimReplayParam)
  })
_sym_db.RegisterMessage(ResimReplayParam)

ResimReplayStatusParam = _reflection.GeneratedProtocolMessageType('ResimReplayStatusParam', (_message.Message,), {
  'DESCRIPTOR' : _RESIMREPLAYSTATUSPARAM,
  '__module__' : 'morai.simulation.resim_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.ResimReplayStatusParam)
  })
_sym_db.RegisterMessage(ResimReplayStatusParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002,CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation'
  _RESIMRECORDPARAM._serialized_start=98
  _RESIMRECORDPARAM._serialized_end=217
  _RESIMRECORDSTATUSPARAM._serialized_start=219
  _RESIMRECORDSTATUSPARAM._serialized_end=308
  _RESIMREPLAYINITPARAM._serialized_start=311
  _RESIMREPLAYINITPARAM._serialized_end=458
  _RESIMREPLAYRANGEPARAM._serialized_start=460
  _RESIMREPLAYRANGEPARAM._serialized_end=511
  _RESIMREPLAYPARAM._serialized_start=513
  _RESIMREPLAYPARAM._serialized_end=570
  _RESIMREPLAYSTATUSPARAM._serialized_start=572
  _RESIMREPLAYSTATUSPARAM._serialized_end=690
# @@protoc_insertion_point(module_scope)
