# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/simulation/simulation_enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&morai/simulation/simulation_enum.proto\x12\x18morai_sim_api.simulation*r\n\x0cSyncModeType\x12\x1e\n\x1aSYNC_MODE_TYPE_UNSPECIFIED\x10\x00\x12\"\n\x1eSYNC_MODE_TYPE_TIME_MANAGEMENT\x10\x01\x12\x1e\n\x1aSYNC_MODE_TYPE_SYNCHRONOUS\x10\x02*\x81\x01\n\x12SimulationModeType\x12\x1f\n\x1bSIMULATION_MODE_TYPE_NORMAL\x10\x00\x12(\n$SIMULATION_MODE_TYPE_SCENARIO_RUNNER\x10\x01\x12 \n\x1cSIMULATION_MODE_TYPE_DATAGEN\x10\x02*r\n\x15ResimRecordStatusType\x12\x1c\n\x18RESIM_RECORD_STATUS_INIT\x10\x00\x12\x1d\n\x19RESIM_RECORD_STATUS_START\x10\x01\x12\x1c\n\x18RESIM_RECORD_STATUS_STOP\x10\x02*\x8f\x01\n\x15ResimReplayStatusType\x12\x1c\n\x18RESIM_REPLAY_STATUS_INIT\x10\x00\x12\x1b\n\x17RESIM_REPLAY_STATUS_RUN\x10\x01\x12\x1c\n\x18RESIM_REPLAY_STATUS_DONE\x10\x02\x12\x1d\n\x19RESIM_REPLAY_STATUS_ERROR\x10\x03\x42\x31H\x01\xaa\x02,CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulationb\x06proto3')

_SYNCMODETYPE = DESCRIPTOR.enum_types_by_name['SyncModeType']
SyncModeType = enum_type_wrapper.EnumTypeWrapper(_SYNCMODETYPE)
_SIMULATIONMODETYPE = DESCRIPTOR.enum_types_by_name['SimulationModeType']
SimulationModeType = enum_type_wrapper.EnumTypeWrapper(_SIMULATIONMODETYPE)
_RESIMRECORDSTATUSTYPE = DESCRIPTOR.enum_types_by_name['ResimRecordStatusType']
ResimRecordStatusType = enum_type_wrapper.EnumTypeWrapper(_RESIMRECORDSTATUSTYPE)
_RESIMREPLAYSTATUSTYPE = DESCRIPTOR.enum_types_by_name['ResimReplayStatusType']
ResimReplayStatusType = enum_type_wrapper.EnumTypeWrapper(_RESIMREPLAYSTATUSTYPE)
SYNC_MODE_TYPE_UNSPECIFIED = 0
SYNC_MODE_TYPE_TIME_MANAGEMENT = 1
SYNC_MODE_TYPE_SYNCHRONOUS = 2
SIMULATION_MODE_TYPE_NORMAL = 0
SIMULATION_MODE_TYPE_SCENARIO_RUNNER = 1
SIMULATION_MODE_TYPE_DATAGEN = 2
RESIM_RECORD_STATUS_INIT = 0
RESIM_RECORD_STATUS_START = 1
RESIM_RECORD_STATUS_STOP = 2
RESIM_REPLAY_STATUS_INIT = 0
RESIM_REPLAY_STATUS_RUN = 1
RESIM_REPLAY_STATUS_DONE = 2
RESIM_REPLAY_STATUS_ERROR = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002,CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation'
  _SYNCMODETYPE._serialized_start=68
  _SYNCMODETYPE._serialized_end=182
  _SIMULATIONMODETYPE._serialized_start=185
  _SIMULATIONMODETYPE._serialized_end=314
  _RESIMRECORDSTATUSTYPE._serialized_start=316
  _RESIMRECORDSTATUSTYPE._serialized_end=430
  _RESIMREPLAYSTATUSTYPE._serialized_start=433
  _RESIMREPLAYSTATUSTYPE._serialized_end=576
# @@protoc_insertion_point(module_scope)
