# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.simulation import resim_pb2 as morai_dot_simulation_dot_resim__pb2
from morai.simulation import start_param_pb2 as morai_dot_simulation_dot_start__param__pb2
from morai.simulation import sync_mode_pb2 as morai_dot_simulation_dot_sync__mode__pb2


class SimulationStub(object):
    """*
    시뮬레이션 시 사용하는 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/Start',
                request_serializer=morai_dot_simulation_dot_start__param__pb2.StartParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.Stop = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/Stop',
                request_serializer=morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.Pause = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/Pause',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.Resume = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/Resume',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetSynchronousMode = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/GetSynchronousMode',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_simulation_dot_sync__mode__pb2.SyncMode.FromString,
                )
        self.SetSynchronousMode = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/SetSynchronousMode',
                request_serializer=morai_dot_simulation_dot_sync__mode__pb2.SyncMode.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.Tick = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/Tick',
                request_serializer=morai_dot_common_dot_type__pb2.Int32Value.SerializeToString,
                response_deserializer=morai_dot_simulation_dot_sync__mode__pb2.SyncTimestamp.FromString,
                )
        self.WaitForTick = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/WaitForTick',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.Int64Value.FromString,
                )
        self.SetSimulationMode = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/SetSimulationMode',
                request_serializer=morai_dot_simulation_dot_start__param__pb2.SimulationModeParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetResimRecordMode = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/SetResimRecordMode',
                request_serializer=morai_dot_simulation_dot_resim__pb2.ResimRecordParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetResimRecordStatus = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/GetResimRecordStatus',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_simulation_dot_resim__pb2.ResimRecordStatusParam.FromString,
                )
        self.ResimReplayInit = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/ResimReplayInit',
                request_serializer=morai_dot_simulation_dot_resim__pb2.ResimReplayInitParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.ResimReplayStart = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/ResimReplayStart',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetResimReplayStatus = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/GetResimReplayStatus',
                request_serializer=morai_dot_common_dot_type__pb2.Empty.SerializeToString,
                response_deserializer=morai_dot_simulation_dot_resim__pb2.ResimReplayStatusParam.FromString,
                )
        self.AddResimReplayRange = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/AddResimReplayRange',
                request_serializer=morai_dot_simulation_dot_resim__pb2.ResimReplayRangeParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/SendMessage',
                request_serializer=morai_dot_simulation_dot_start__param__pb2.SendMessageParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SendStringListMessage = channel.unary_unary(
                '/morai_sim_api.simulation.Simulation/SendStringListMessage',
                request_serializer=morai_dot_simulation_dot_start__param__pb2.StringListParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )


class SimulationServicer(object):
    """*
    시뮬레이션 시 사용하는 서비스
    """

    def Start(self, request, context):
        """* 
        시뮬레이션 시작
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """*
        시뮬레이션 종료
        client_key 값으로 생성된 차량을 삭제함
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """*
        시뮬레이션 일시 정지
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """*
        시뮬레이션 재개
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSynchronousMode(self, request, context):
        """*
        시뮬레이션 모드 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSynchronousMode(self, request, context):
        """*
        시뮬레이션 모드 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tick(self, request, context):
        """*
        동기 모드일 때 설정한 횟수만큼 Tick 진행
        unit : tick count
        response : frame index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForTick(self, request, context):
        """*
        비동기 모드일 때 사용하는 rpc로 다음 틱이 돌아오면 리턴
        response : timestamp (msec)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSimulationMode(self, request, context):
        """*
        Simulation Mode setting
        // 1. Normal, 2. Scenario runner, 3. Datagen, 4.....
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetResimRecordMode(self, request, context):
        """*
        Resim Record 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResimRecordStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResimReplayInit(self, request, context):
        """*
        Resim Replay

        rpc SetResimReplayMode(ResimReplayParam) returns (Result);    

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResimReplayStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResimReplayStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddResimReplayRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """*
        General message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStringListMessage(self, request, context):
        """
        String List for Custom
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=morai_dot_simulation_dot_start__param__pb2.StartParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=morai_dot_common_dot_type__pb2.StringValue.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetSynchronousMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSynchronousMode,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_simulation_dot_sync__mode__pb2.SyncMode.SerializeToString,
            ),
            'SetSynchronousMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSynchronousMode,
                    request_deserializer=morai_dot_simulation_dot_sync__mode__pb2.SyncMode.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'Tick': grpc.unary_unary_rpc_method_handler(
                    servicer.Tick,
                    request_deserializer=morai_dot_common_dot_type__pb2.Int32Value.FromString,
                    response_serializer=morai_dot_simulation_dot_sync__mode__pb2.SyncTimestamp.SerializeToString,
            ),
            'WaitForTick': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitForTick,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.Int64Value.SerializeToString,
            ),
            'SetSimulationMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSimulationMode,
                    request_deserializer=morai_dot_simulation_dot_start__param__pb2.SimulationModeParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetResimRecordMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetResimRecordMode,
                    request_deserializer=morai_dot_simulation_dot_resim__pb2.ResimRecordParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetResimRecordStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResimRecordStatus,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_simulation_dot_resim__pb2.ResimRecordStatusParam.SerializeToString,
            ),
            'ResimReplayInit': grpc.unary_unary_rpc_method_handler(
                    servicer.ResimReplayInit,
                    request_deserializer=morai_dot_simulation_dot_resim__pb2.ResimReplayInitParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'ResimReplayStart': grpc.unary_unary_rpc_method_handler(
                    servicer.ResimReplayStart,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetResimReplayStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResimReplayStatus,
                    request_deserializer=morai_dot_common_dot_type__pb2.Empty.FromString,
                    response_serializer=morai_dot_simulation_dot_resim__pb2.ResimReplayStatusParam.SerializeToString,
            ),
            'AddResimReplayRange': grpc.unary_unary_rpc_method_handler(
                    servicer.AddResimReplayRange,
                    request_deserializer=morai_dot_simulation_dot_resim__pb2.ResimReplayRangeParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=morai_dot_simulation_dot_start__param__pb2.SendMessageParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SendStringListMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStringListMessage,
                    request_deserializer=morai_dot_simulation_dot_start__param__pb2.StringListParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.simulation.Simulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulation(object):
    """*
    시뮬레이션 시 사용하는 서비스
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/Start',
            morai_dot_simulation_dot_start__param__pb2.StartParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/Stop',
            morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/Pause',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/Resume',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSynchronousMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/GetSynchronousMode',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_simulation_dot_sync__mode__pb2.SyncMode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSynchronousMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/SetSynchronousMode',
            morai_dot_simulation_dot_sync__mode__pb2.SyncMode.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Tick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/Tick',
            morai_dot_common_dot_type__pb2.Int32Value.SerializeToString,
            morai_dot_simulation_dot_sync__mode__pb2.SyncTimestamp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WaitForTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/WaitForTick',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_type__pb2.Int64Value.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSimulationMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/SetSimulationMode',
            morai_dot_simulation_dot_start__param__pb2.SimulationModeParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetResimRecordMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/SetResimRecordMode',
            morai_dot_simulation_dot_resim__pb2.ResimRecordParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResimRecordStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/GetResimRecordStatus',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_simulation_dot_resim__pb2.ResimRecordStatusParam.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResimReplayInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/ResimReplayInit',
            morai_dot_simulation_dot_resim__pb2.ResimReplayInitParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResimReplayStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/ResimReplayStart',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResimReplayStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/GetResimReplayStatus',
            morai_dot_common_dot_type__pb2.Empty.SerializeToString,
            morai_dot_simulation_dot_resim__pb2.ResimReplayStatusParam.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddResimReplayRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/AddResimReplayRange',
            morai_dot_simulation_dot_resim__pb2.ResimReplayRangeParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/SendMessage',
            morai_dot_simulation_dot_start__param__pb2.SendMessageParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendStringListMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.simulation.Simulation/SendStringListMessage',
            morai_dot_simulation_dot_start__param__pb2.StringListParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
