# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/simulation/start_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.simulation import sync_mode_pb2 as morai_dot_simulation_dot_sync__mode__pb2
from morai.actor import actor_set_pb2 as morai_dot_actor_dot_actor__set__pb2
from morai.simulation import simulation_enum_pb2 as morai_dot_simulation_dot_simulation__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"morai/simulation/start_param.proto\x12\x18morai_sim_api.simulation\x1a\x17morai/common/type.proto\x1a morai/simulation/sync_mode.proto\x1a\x1bmorai/actor/actor_set.proto\x1a&morai/simulation/simulation_enum.proto\"\x89\x03\n\nStartParam\x12@\n\x0fmap_and_vehicle\x18\x01 \x01(\x0b\x32\'.morai_sim_api.simulation.MapAndVehicle\x12\x34\n\x0b\x65go_setting\x18\x02 \x01(\x0b\x32\x1f.morai_sim_api.actor.EgoSetting\x12/\n\rego_transform\x18\x03 \x01(\x0b\x32\x18.morai_sim_api.Transform\x12\x41\n\x12\x65go_cruise_setting\x18\x04 \x01(\x0b\x32%.morai_sim_api.actor.EgoCruiseControl\x12\x30\n\x04mode\x18\x05 \x01(\x0b\x32\".morai_sim_api.simulation.SyncMode\x12I\n\x13simulation_settings\x18\x07 \x01(\x0b\x32,.morai_sim_api.simulation.SimulationSettings\x12\x12\n\nclient_key\x18\x08 \x01(\t\"<\n\rMapAndVehicle\x12\x10\n\x08map_name\x18\x01 \x01(\t\x12\x19\n\x11\x65go_vehicle_model\x18\x02 \x01(\t\"V\n\x12SimulationSettings\x12\x1f\n\x17morai_scenario_filename\x18\x01 \x01(\t\x12\x1f\n\x17sensor_setting_filename\x18\x02 \x01(\t\"Q\n\x13SimulationModeParam\x12:\n\x04mode\x18\x01 \x01(\x0e\x32,.morai_sim_api.simulation.SimulationModeType\"1\n\x10SendMessageParam\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0fStringListParam\x12\x0f\n\x07message\x18\x01 \x01(\tB1H\x01\xaa\x02,CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulationb\x06proto3')



_STARTPARAM = DESCRIPTOR.message_types_by_name['StartParam']
_MAPANDVEHICLE = DESCRIPTOR.message_types_by_name['MapAndVehicle']
_SIMULATIONSETTINGS = DESCRIPTOR.message_types_by_name['SimulationSettings']
_SIMULATIONMODEPARAM = DESCRIPTOR.message_types_by_name['SimulationModeParam']
_SENDMESSAGEPARAM = DESCRIPTOR.message_types_by_name['SendMessageParam']
_STRINGLISTPARAM = DESCRIPTOR.message_types_by_name['StringListParam']
StartParam = _reflection.GeneratedProtocolMessageType('StartParam', (_message.Message,), {
  'DESCRIPTOR' : _STARTPARAM,
  '__module__' : 'morai.simulation.start_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.StartParam)
  })
_sym_db.RegisterMessage(StartParam)

MapAndVehicle = _reflection.GeneratedProtocolMessageType('MapAndVehicle', (_message.Message,), {
  'DESCRIPTOR' : _MAPANDVEHICLE,
  '__module__' : 'morai.simulation.start_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.MapAndVehicle)
  })
_sym_db.RegisterMessage(MapAndVehicle)

SimulationSettings = _reflection.GeneratedProtocolMessageType('SimulationSettings', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONSETTINGS,
  '__module__' : 'morai.simulation.start_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.SimulationSettings)
  })
_sym_db.RegisterMessage(SimulationSettings)

SimulationModeParam = _reflection.GeneratedProtocolMessageType('SimulationModeParam', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONMODEPARAM,
  '__module__' : 'morai.simulation.start_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.SimulationModeParam)
  })
_sym_db.RegisterMessage(SimulationModeParam)

SendMessageParam = _reflection.GeneratedProtocolMessageType('SendMessageParam', (_message.Message,), {
  'DESCRIPTOR' : _SENDMESSAGEPARAM,
  '__module__' : 'morai.simulation.start_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.SendMessageParam)
  })
_sym_db.RegisterMessage(SendMessageParam)

StringListParam = _reflection.GeneratedProtocolMessageType('StringListParam', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLISTPARAM,
  '__module__' : 'morai.simulation.start_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.StringListParam)
  })
_sym_db.RegisterMessage(StringListParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002,CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation'
  _STARTPARAM._serialized_start=193
  _STARTPARAM._serialized_end=586
  _MAPANDVEHICLE._serialized_start=588
  _MAPANDVEHICLE._serialized_end=648
  _SIMULATIONSETTINGS._serialized_start=650
  _SIMULATIONSETTINGS._serialized_end=736
  _SIMULATIONMODEPARAM._serialized_start=738
  _SIMULATIONMODEPARAM._serialized_end=819
  _SENDMESSAGEPARAM._serialized_start=821
  _SENDMESSAGEPARAM._serialized_end=870
  _STRINGLISTPARAM._serialized_start=872
  _STRINGLISTPARAM._serialized_end=906
# @@protoc_insertion_point(module_scope)
