# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/simulation/sync_mode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.simulation import simulation_enum_pb2 as morai_dot_simulation_dot_simulation__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n morai/simulation/sync_mode.proto\x12\x18morai_sim_api.simulation\x1a&morai/simulation/simulation_enum.proto\"U\n\x08SyncMode\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.morai_sim_api.simulation.SyncModeType\x12\x13\n\x0btick_period\x18\x02 \x01(\x05\":\n\rSyncTimestamp\x12\x13\n\x0b\x66rame_count\x18\x01 \x01(\x04\x12\x14\n\x0c\x65lapsed_time\x18\x02 \x01(\x03\x42\x31H\x01\xaa\x02,CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulationb\x06proto3')



_SYNCMODE = DESCRIPTOR.message_types_by_name['SyncMode']
_SYNCTIMESTAMP = DESCRIPTOR.message_types_by_name['SyncTimestamp']
SyncMode = _reflection.GeneratedProtocolMessageType('SyncMode', (_message.Message,), {
  'DESCRIPTOR' : _SYNCMODE,
  '__module__' : 'morai.simulation.sync_mode_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.SyncMode)
  })
_sym_db.RegisterMessage(SyncMode)

SyncTimestamp = _reflection.GeneratedProtocolMessageType('SyncTimestamp', (_message.Message,), {
  'DESCRIPTOR' : _SYNCTIMESTAMP,
  '__module__' : 'morai.simulation.sync_mode_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.simulation.SyncTimestamp)
  })
_sym_db.RegisterMessage(SyncTimestamp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002,CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation'
  _SYNCMODE._serialized_start=102
  _SYNCMODE._serialized_end=187
  _SYNCTIMESTAMP._serialized_start=189
  _SYNCTIMESTAMP._serialized_end=247
# @@protoc_insertion_point(module_scope)
