# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/sensor/add_sensor_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2
from morai.sensor import sensor_enum_pb2 as morai_dot_sensor_dot_sensor__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#morai/sensor/add_sensor_param.proto\x12\x14morai_sim_api.sensor\x1a\x17morai/common/type.proto\x1a\x1emorai/common/object_info.proto\x1a\x1emorai/sensor/sensor_enum.proto\"\xa3\x01\n\x0e\x41\x64\x64SensorParam\x12-\n\nvehicle_id\x18\x01 \x01(\x0b\x32\x19.morai_sim_api.ObjectInfo\x12\x35\n\x0bsensor_type\x18\x02 \x01(\x0e\x32 .morai_sim_api.sensor.SensorType\x12+\n\ttransform\x18\x03 \x01(\x0b\x32\x18.morai_sim_api.Transform\"L\n\x12\x41\x64\x64SensorParamList\x12\x36\n\x08req_list\x18\x01 \x03(\x0b\x32$.morai_sim_api.sensor.AddSensorParamB-H\x01\xaa\x02(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensorb\x06proto3')



_ADDSENSORPARAM = DESCRIPTOR.message_types_by_name['AddSensorParam']
_ADDSENSORPARAMLIST = DESCRIPTOR.message_types_by_name['AddSensorParamList']
AddSensorParam = _reflection.GeneratedProtocolMessageType('AddSensorParam', (_message.Message,), {
  'DESCRIPTOR' : _ADDSENSORPARAM,
  '__module__' : 'morai.sensor.add_sensor_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.sensor.AddSensorParam)
  })
_sym_db.RegisterMessage(AddSensorParam)

AddSensorParamList = _reflection.GeneratedProtocolMessageType('AddSensorParamList', (_message.Message,), {
  'DESCRIPTOR' : _ADDSENSORPARAMLIST,
  '__module__' : 'morai.sensor.add_sensor_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.sensor.AddSensorParamList)
  })
_sym_db.RegisterMessage(AddSensorParamList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor'
  _ADDSENSORPARAM._serialized_start=151
  _ADDSENSORPARAM._serialized_end=314
  _ADDSENSORPARAMLIST._serialized_start=316
  _ADDSENSORPARAMLIST._serialized_end=392
# @@protoc_insertion_point(module_scope)
