# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/sensor/sensor_data_save_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*morai/sensor/sensor_data_save_config.proto\x12\x14morai_sim_api.sensor\"_\n\x14SensorDataSaveConfig\x12\x1b\n\x13is_custom_file_name\x18\x01 \x01(\x08\x12\x18\n\x10\x63ustom_file_name\x18\x02 \x01(\t\x12\x10\n\x08\x66ile_dir\x18\x03 \x01(\tB-H\x01\xaa\x02(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensorb\x06proto3')



_SENSORDATASAVECONFIG = DESCRIPTOR.message_types_by_name['SensorDataSaveConfig']
SensorDataSaveConfig = _reflection.GeneratedProtocolMessageType('SensorDataSaveConfig', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATASAVECONFIG,
  '__module__' : 'morai.sensor.sensor_data_save_config_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.sensor.SensorDataSaveConfig)
  })
_sym_db.RegisterMessage(SensorDataSaveConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor'
  _SENSORDATASAVECONFIG._serialized_start=68
  _SENSORDATASAVECONFIG._serialized_end=163
# @@protoc_insertion_point(module_scope)
