# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/sensor/sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.sensor import sensor_settings_pb2 as morai_dot_sensor_dot_sensor__settings__pb2
from morai.sensor import sensor_info_pb2 as morai_dot_sensor_dot_sensor__info__pb2
from morai.sensor import sensor_data_save_config_pb2 as morai_dot_sensor_dot_sensor__data__save__config__pb2
from morai.sensor import sensor_data_pb2 as morai_dot_sensor_dot_sensor__data__pb2
from morai.sensor import add_sensor_param_pb2 as morai_dot_sensor_dot_add__sensor__param__pb2
from morai.sensor import sensor_result_pb2 as morai_dot_sensor_dot_sensor__result__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2
from morai.common import object_identifier_pb2 as morai_dot_common_dot_object__identifier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19morai/sensor/sensor.proto\x12\x14morai_sim_api.sensor\x1a\x17morai/common/type.proto\x1a\x19morai/common/result.proto\x1a\"morai/sensor/sensor_settings.proto\x1a\x1emorai/sensor/sensor_info.proto\x1a*morai/sensor/sensor_data_save_config.proto\x1a\x1emorai/sensor/sensor_data.proto\x1a#morai/sensor/add_sensor_param.proto\x1a morai/sensor/sensor_result.proto\x1a\x1emorai/common/object_info.proto\x1a$morai/common/object_identifier.proto2\xee\x07\n\x06Sensor\x12H\n\tAddSensor\x12$.morai_sim_api.sensor.AddSensorParam\x1a\x15.morai_sim_api.Result\x12G\n\x0cRemoveSensor\x12 .morai_sim_api.sensor.SensorInfo\x1a\x15.morai_sim_api.Result\x12N\n\x10SetSensorSetting\x12#.morai_sim_api.sensor.SensorSetting\x1a\x15.morai_sim_api.Result\x12S\n\rGetSensorData\x12 .morai_sim_api.sensor.SensorInfo\x1a .morai_sim_api.sensor.SensorData\x12S\n\x0eSaveSensorData\x12*.morai_sim_api.sensor.SensorDataSaveConfig\x1a\x15.morai_sim_api.Result\x12\x43\n\x0eLoadSensorFile\x12\x1a.morai_sim_api.StringValue\x1a\x15.morai_sim_api.Result\x12N\n\x0eGetSensorInfos\x12\x19.morai_sim_api.ObjectInfo\x1a!.morai_sim_api.sensor.SensorInfos\x12[\n\x14SetSensorCaptureMode\x12,.morai_sim_api.sensor.SensorCaptureModeParam\x1a\x15.morai_sim_api.Result\x12N\n\x14GetSensorCaptureMode\x12\x1f.morai_sim_api.ObjectIdentifier\x1a\x15.morai_sim_api.Result\x12Y\n\x13SetSensorMuteByType\x12+.morai_sim_api.sensor.SensorMuteByTypeParam\x1a\x15.morai_sim_api.Result\x12V\n\x0eSetSensorFault\x12!.morai_sim_api.sensor.SensorFault\x1a!.morai_sim_api.sensor.FaultResult\x12\x62\n\x10SetWeatherEffect\x12#.morai_sim_api.sensor.WeatherEffect\x1a).morai_sim_api.sensor.WeatherEffectResultB-H\x01\xaa\x02(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensorb\x06proto3')



_SENSOR = DESCRIPTOR.services_by_name['Sensor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor'
  _SENSOR._serialized_start=389
  _SENSOR._serialized_end=1395
# @@protoc_insertion_point(module_scope)
