# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.common import object_identifier_pb2 as morai_dot_common_dot_object__identifier__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2
from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.sensor import add_sensor_param_pb2 as morai_dot_sensor_dot_add__sensor__param__pb2
from morai.sensor import sensor_data_pb2 as morai_dot_sensor_dot_sensor__data__pb2
from morai.sensor import sensor_data_save_config_pb2 as morai_dot_sensor_dot_sensor__data__save__config__pb2
from morai.sensor import sensor_info_pb2 as morai_dot_sensor_dot_sensor__info__pb2
from morai.sensor import sensor_result_pb2 as morai_dot_sensor_dot_sensor__result__pb2
from morai.sensor import sensor_settings_pb2 as morai_dot_sensor_dot_sensor__settings__pb2


class SensorStub(object):
    """*
    Sensor 관련 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSensor = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/AddSensor',
                request_serializer=morai_dot_sensor_dot_add__sensor__param__pb2.AddSensorParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.RemoveSensor = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/RemoveSensor',
                request_serializer=morai_dot_sensor_dot_sensor__info__pb2.SensorInfo.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetSensorSetting = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/SetSensorSetting',
                request_serializer=morai_dot_sensor_dot_sensor__settings__pb2.SensorSetting.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetSensorData = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/GetSensorData',
                request_serializer=morai_dot_sensor_dot_sensor__info__pb2.SensorInfo.SerializeToString,
                response_deserializer=morai_dot_sensor_dot_sensor__data__pb2.SensorData.FromString,
                )
        self.SaveSensorData = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/SaveSensorData',
                request_serializer=morai_dot_sensor_dot_sensor__data__save__config__pb2.SensorDataSaveConfig.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.LoadSensorFile = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/LoadSensorFile',
                request_serializer=morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetSensorInfos = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/GetSensorInfos',
                request_serializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
                response_deserializer=morai_dot_sensor_dot_sensor__info__pb2.SensorInfos.FromString,
                )
        self.SetSensorCaptureMode = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/SetSensorCaptureMode',
                request_serializer=morai_dot_sensor_dot_sensor__settings__pb2.SensorCaptureModeParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetSensorCaptureMode = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/GetSensorCaptureMode',
                request_serializer=morai_dot_common_dot_object__identifier__pb2.ObjectIdentifier.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetSensorMuteByType = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/SetSensorMuteByType',
                request_serializer=morai_dot_sensor_dot_sensor__settings__pb2.SensorMuteByTypeParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetSensorFault = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/SetSensorFault',
                request_serializer=morai_dot_sensor_dot_sensor__settings__pb2.SensorFault.SerializeToString,
                response_deserializer=morai_dot_sensor_dot_sensor__result__pb2.FaultResult.FromString,
                )
        self.SetWeatherEffect = channel.unary_unary(
                '/morai_sim_api.sensor.Sensor/SetWeatherEffect',
                request_serializer=morai_dot_sensor_dot_sensor__settings__pb2.WeatherEffect.SerializeToString,
                response_deserializer=morai_dot_sensor_dot_sensor__result__pb2.WeatherEffectResult.FromString,
                )


class SensorServicer(object):
    """*
    Sensor 관련 서비스
    """

    def AddSensor(self, request, context):
        """Install the sensor on the vehicle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSensor(self, request, context):
        """Remove the sensors installed on the vehicle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSensorSetting(self, request, context):
        """set sensor setting (GT sensor only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensorData(self, request, context):
        """get sensor setting info (GT Sensor only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSensorData(self, request, context):
        """Save all sensor settings to a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSensorFile(self, request, context):
        """Load a preset sensor setup file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensorInfos(self, request, context):
        """List of Sensors installed on the vehicle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSensorCaptureMode(self, request, context):
        """Turn on sensor capture mode 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensorCaptureMode(self, request, context):
        """Get sens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSensorMuteByType(self, request, context):
        """Sensor Mute
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSensorFault(self, request, context):
        """Sensor Fault
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWeatherEffect(self, request, context):
        """Sensor Weather Effect
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSensor,
                    request_deserializer=morai_dot_sensor_dot_add__sensor__param__pb2.AddSensorParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'RemoveSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSensor,
                    request_deserializer=morai_dot_sensor_dot_sensor__info__pb2.SensorInfo.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetSensorSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSensorSetting,
                    request_deserializer=morai_dot_sensor_dot_sensor__settings__pb2.SensorSetting.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorData,
                    request_deserializer=morai_dot_sensor_dot_sensor__info__pb2.SensorInfo.FromString,
                    response_serializer=morai_dot_sensor_dot_sensor__data__pb2.SensorData.SerializeToString,
            ),
            'SaveSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveSensorData,
                    request_deserializer=morai_dot_sensor_dot_sensor__data__save__config__pb2.SensorDataSaveConfig.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'LoadSensorFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSensorFile,
                    request_deserializer=morai_dot_common_dot_type__pb2.StringValue.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetSensorInfos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorInfos,
                    request_deserializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.FromString,
                    response_serializer=morai_dot_sensor_dot_sensor__info__pb2.SensorInfos.SerializeToString,
            ),
            'SetSensorCaptureMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSensorCaptureMode,
                    request_deserializer=morai_dot_sensor_dot_sensor__settings__pb2.SensorCaptureModeParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetSensorCaptureMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorCaptureMode,
                    request_deserializer=morai_dot_common_dot_object__identifier__pb2.ObjectIdentifier.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetSensorMuteByType': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSensorMuteByType,
                    request_deserializer=morai_dot_sensor_dot_sensor__settings__pb2.SensorMuteByTypeParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetSensorFault': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSensorFault,
                    request_deserializer=morai_dot_sensor_dot_sensor__settings__pb2.SensorFault.FromString,
                    response_serializer=morai_dot_sensor_dot_sensor__result__pb2.FaultResult.SerializeToString,
            ),
            'SetWeatherEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWeatherEffect,
                    request_deserializer=morai_dot_sensor_dot_sensor__settings__pb2.WeatherEffect.FromString,
                    response_serializer=morai_dot_sensor_dot_sensor__result__pb2.WeatherEffectResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.sensor.Sensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sensor(object):
    """*
    Sensor 관련 서비스
    """

    @staticmethod
    def AddSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/AddSensor',
            morai_dot_sensor_dot_add__sensor__param__pb2.AddSensorParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/RemoveSensor',
            morai_dot_sensor_dot_sensor__info__pb2.SensorInfo.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSensorSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/SetSensorSetting',
            morai_dot_sensor_dot_sensor__settings__pb2.SensorSetting.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/GetSensorData',
            morai_dot_sensor_dot_sensor__info__pb2.SensorInfo.SerializeToString,
            morai_dot_sensor_dot_sensor__data__pb2.SensorData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/SaveSensorData',
            morai_dot_sensor_dot_sensor__data__save__config__pb2.SensorDataSaveConfig.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadSensorFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/LoadSensorFile',
            morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSensorInfos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/GetSensorInfos',
            morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
            morai_dot_sensor_dot_sensor__info__pb2.SensorInfos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSensorCaptureMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/SetSensorCaptureMode',
            morai_dot_sensor_dot_sensor__settings__pb2.SensorCaptureModeParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSensorCaptureMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/GetSensorCaptureMode',
            morai_dot_common_dot_object__identifier__pb2.ObjectIdentifier.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSensorMuteByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/SetSensorMuteByType',
            morai_dot_sensor_dot_sensor__settings__pb2.SensorMuteByTypeParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSensorFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/SetSensorFault',
            morai_dot_sensor_dot_sensor__settings__pb2.SensorFault.SerializeToString,
            morai_dot_sensor_dot_sensor__result__pb2.FaultResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetWeatherEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.sensor.Sensor/SetWeatherEffect',
            morai_dot_sensor_dot_sensor__settings__pb2.WeatherEffect.SerializeToString,
            morai_dot_sensor_dot_sensor__result__pb2.WeatherEffectResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
