# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/sensor/sensor_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import object_identifier_pb2 as morai_dot_common_dot_object__identifier__pb2
from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.sensor import sensor_info_pb2 as morai_dot_sensor_dot_sensor__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emorai/sensor/sensor_data.proto\x12\x14morai_sim_api.sensor\x1a$morai/common/object_identifier.proto\x1a\x17morai/common/type.proto\x1a\x1emorai/sensor/sensor_info.proto\"\x87\x01\n\nSensorData\x12\x35\n\x0bsensor_info\x18\x01 \x01(\x0b\x32 .morai_sim_api.sensor.SensorInfo\x12\x39\n\x0cground_truth\x18\x02 \x01(\x0b\x32!.morai_sim_api.sensor.GroundTruthH\x00\x42\x07\n\x05Value\"\x90\x02\n\x0cObjectStatus\x12+\n\x02id\x18\x01 \x01(\x0b\x32\x1f.morai_sim_api.ObjectIdentifier\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07heading\x18\x04 \x01(\x01\x12(\n\x08position\x18\x05 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12,\n\x0c\x61\x63\x63\x65leration\x18\x06 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12(\n\x08velocity\x18\x07 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12$\n\x04size\x18\x08 \x01(\x0b\x32\x16.morai_sim_api.Vector3\"?\n\x0bGroundTruth\x12\x30\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\".morai_sim_api.sensor.ObjectStatusB-H\x01\xaa\x02(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensorb\x06proto3')



_SENSORDATA = DESCRIPTOR.message_types_by_name['SensorData']
_OBJECTSTATUS = DESCRIPTOR.message_types_by_name['ObjectStatus']
_GROUNDTRUTH = DESCRIPTOR.message_types_by_name['GroundTruth']
SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATA,
  '__module__' : 'morai.sensor.sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.sensor.SensorData)
  })
_sym_db.RegisterMessage(SensorData)

ObjectStatus = _reflection.GeneratedProtocolMessageType('ObjectStatus', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTSTATUS,
  '__module__' : 'morai.sensor.sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.sensor.ObjectStatus)
  })
_sym_db.RegisterMessage(ObjectStatus)

GroundTruth = _reflection.GeneratedProtocolMessageType('GroundTruth', (_message.Message,), {
  'DESCRIPTOR' : _GROUNDTRUTH,
  '__module__' : 'morai.sensor.sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.sensor.GroundTruth)
  })
_sym_db.RegisterMessage(GroundTruth)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor'
  _SENSORDATA._serialized_start=152
  _SENSORDATA._serialized_end=287
  _OBJECTSTATUS._serialized_start=290
  _OBJECTSTATUS._serialized_end=562
  _GROUNDTRUTH._serialized_start=564
  _GROUNDTRUTH._serialized_end=627
# @@protoc_insertion_point(module_scope)
