# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/sensor/sensor_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2
from morai.common import resource_identifier_pb2 as morai_dot_common_dot_resource__identifier__pb2
from morai.sensor import sensor_enum_pb2 as morai_dot_sensor_dot_sensor__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emorai/sensor/sensor_info.proto\x12\x14morai_sim_api.sensor\x1a\x1emorai/common/object_info.proto\x1a&morai/common/resource_identifier.proto\x1a\x1emorai/sensor/sensor_enum.proto\"\xaa\x01\n\nSensorInfo\x12/\n\x0cvehicle_info\x18\x01 \x01(\x0b\x32\x19.morai_sim_api.ObjectInfo\x12\x34\n\tsensor_id\x18\x02 \x01(\x0b\x32!.morai_sim_api.ResourceIdentifier\x12\x35\n\x0bsensor_type\x18\x03 \x01(\x0e\x32 .morai_sim_api.sensor.SensorType\"?\n\x0bSensorInfos\x12\x30\n\x06values\x18\x01 \x03(\x0b\x32 .morai_sim_api.sensor.SensorInfoB-H\x01\xaa\x02(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensorb\x06proto3')



_SENSORINFO = DESCRIPTOR.message_types_by_name['SensorInfo']
_SENSORINFOS = DESCRIPTOR.message_types_by_name['SensorInfos']
SensorInfo = _reflection.GeneratedProtocolMessageType('SensorInfo', (_message.Message,), {
  'DESCRIPTOR' : _SENSORINFO,
  '__module__' : 'morai.sensor.sensor_info_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.sensor.SensorInfo)
  })
_sym_db.RegisterMessage(SensorInfo)

SensorInfos = _reflection.GeneratedProtocolMessageType('SensorInfos', (_message.Message,), {
  'DESCRIPTOR' : _SENSORINFOS,
  '__module__' : 'morai.sensor.sensor_info_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.sensor.SensorInfos)
  })
_sym_db.RegisterMessage(SensorInfos)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor'
  _SENSORINFO._serialized_start=161
  _SENSORINFO._serialized_end=331
  _SENSORINFOS._serialized_start=333
  _SENSORINFOS._serialized_end=396
# @@protoc_insertion_point(module_scope)
