# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/sensor/sensor_enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emorai/sensor/sensor_enum.proto\x12\x14morai_sim_api.sensor*\xe6\x02\n\nSensorType\x12\x1b\n\x17SENSOR_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12SENSOR_TYPE_CAMERA\x10\x01\x12\x17\n\x13SENSOR_TYPE_LIDAR3D\x10\x02\x12\x17\n\x13SENSOR_TYPE_LIDAR2D\x10\x03\x12\x13\n\x0fSENSOR_TYPE_GPS\x10\x04\x12\x13\n\x0fSENSOR_TYPE_IMU\x10\x05\x12\x15\n\x11SENSOR_TYPE_RADAR\x10\x06\x12\x1a\n\x16SENSOR_TYPE_ULTRASONIC\x10\x07\x12\x1b\n\x17SENSOR_TYPE_GROUNDTRUTH\x10\x08\x12\x18\n\x14SENSOR_TYPE_VELARRAY\x10\t\x12\x15\n\x11SENSOR_TYPE_LIGHT\x10\n\x12\x1c\n\x18SENSOR_TYPE_DELPHI_RADAR\x10\x0b\x12\x13\n\x0fSENSRO_TYPE_TOF\x10\x0c\x12\x13\n\x0fSENSOR_TYPE_END\x10\r*c\n\x0bGTShapeType\x12\x18\n\x14GT_SHAPE_UNSPECIFIED\x10\x00\x12\x15\n\x11GT_SHAPE_CYLINDER\x10\x01\x12\x11\n\rGT_SHAPE_CONE\x10\x02\x12\x10\n\x0cGT_SHAPE_END\x10\x03*\xf8\x03\n\x11GTObstacleObjType\x12\x1b\n\x17GT_OBSTACLE_OBJ_INKNOWN\x10\x00\x12\x1b\n\x17GT_OBSTACLE_OBJ_VEHICLE\x10\x01\x12\x1e\n\x1aGT_OBSTACLE_OBJ_PEDESTRIAN\x10\x02\x12\x1e\n\x1aGT_OBSTACLE_OBJ_EGOVEHICLE\x10\x03\x12\x1c\n\x18GT_OBSTACLE_OBJ_OBSTACLE\x10\x04\x12\x1e\n\x1aGT_OBSTACLE_OBJ_SPAWNPOINT\x10\x05\x12 \n\x1cGT_OBSTACLE_OBJ_MOVINGOBJECT\x10\x06\x12!\n\x1dGT_OBSTACLE_OBJ_EXTRAOBSTACLE\x10\x07\x12#\n\x1fGT_OBSTACLE_OBJ_SSAFYSPAWNPOINT\x10\x08\x12$\n GT_OBSTACLE_OBJ_DESTINATIONPOINT\x10\t\x12!\n\x1dGT_OBSTACLE_OBJ_STOPOVERPOINT\x10\n\x12!\n\x1dGT_OBSTACLE_OBJ_PEDSPAWNPOINT\x10\x0b\x12\x1e\n\x1aGT_OBSTACLE_OBJ_SHADEDAREA\x10\x0c\x12\x1d\n\x19GT_OBSTACLE_OBJ_MAPOBJECT\x10\r\x12\x16\n\x12GT_OBSTACL_OBJ_MAX\x10\x0e*`\n\rDataQualifier\x12\x17\n\x13\x44\x41TA_QUALIFIER_NONE\x10\x00\x12\x18\n\x14\x44\x41TA_QUALIFIER_OTHER\x10\x01\x12\x1c\n\x18\x44\x41TA_QUALIFIER_BLINDNESS\x10\x02*)\n\tFaultType\x12\x08\n\x04None\x10\x00\x12\x08\n\x04\x42lur\x10\x01\x12\x08\n\x04\x44ust\x10\x02\x42-H\x01\xaa\x02(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensorb\x06proto3')

_SENSORTYPE = DESCRIPTOR.enum_types_by_name['SensorType']
SensorType = enum_type_wrapper.EnumTypeWrapper(_SENSORTYPE)
_GTSHAPETYPE = DESCRIPTOR.enum_types_by_name['GTShapeType']
GTShapeType = enum_type_wrapper.EnumTypeWrapper(_GTSHAPETYPE)
_GTOBSTACLEOBJTYPE = DESCRIPTOR.enum_types_by_name['GTObstacleObjType']
GTObstacleObjType = enum_type_wrapper.EnumTypeWrapper(_GTOBSTACLEOBJTYPE)
_DATAQUALIFIER = DESCRIPTOR.enum_types_by_name['DataQualifier']
DataQualifier = enum_type_wrapper.EnumTypeWrapper(_DATAQUALIFIER)
_FAULTTYPE = DESCRIPTOR.enum_types_by_name['FaultType']
FaultType = enum_type_wrapper.EnumTypeWrapper(_FAULTTYPE)
SENSOR_TYPE_UNSPECIFIED = 0
SENSOR_TYPE_CAMERA = 1
SENSOR_TYPE_LIDAR3D = 2
SENSOR_TYPE_LIDAR2D = 3
SENSOR_TYPE_GPS = 4
SENSOR_TYPE_IMU = 5
SENSOR_TYPE_RADAR = 6
SENSOR_TYPE_ULTRASONIC = 7
SENSOR_TYPE_GROUNDTRUTH = 8
SENSOR_TYPE_VELARRAY = 9
SENSOR_TYPE_LIGHT = 10
SENSOR_TYPE_DELPHI_RADAR = 11
SENSRO_TYPE_TOF = 12
SENSOR_TYPE_END = 13
GT_SHAPE_UNSPECIFIED = 0
GT_SHAPE_CYLINDER = 1
GT_SHAPE_CONE = 2
GT_SHAPE_END = 3
GT_OBSTACLE_OBJ_INKNOWN = 0
GT_OBSTACLE_OBJ_VEHICLE = 1
GT_OBSTACLE_OBJ_PEDESTRIAN = 2
GT_OBSTACLE_OBJ_EGOVEHICLE = 3
GT_OBSTACLE_OBJ_OBSTACLE = 4
GT_OBSTACLE_OBJ_SPAWNPOINT = 5
GT_OBSTACLE_OBJ_MOVINGOBJECT = 6
GT_OBSTACLE_OBJ_EXTRAOBSTACLE = 7
GT_OBSTACLE_OBJ_SSAFYSPAWNPOINT = 8
GT_OBSTACLE_OBJ_DESTINATIONPOINT = 9
GT_OBSTACLE_OBJ_STOPOVERPOINT = 10
GT_OBSTACLE_OBJ_PEDSPAWNPOINT = 11
GT_OBSTACLE_OBJ_SHADEDAREA = 12
GT_OBSTACLE_OBJ_MAPOBJECT = 13
GT_OBSTACL_OBJ_MAX = 14
DATA_QUALIFIER_NONE = 0
DATA_QUALIFIER_OTHER = 1
DATA_QUALIFIER_BLINDNESS = 2
globals()['None'] = 0
Blur = 1
Dust = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002(CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor'
  _SENSORTYPE._serialized_start=57
  _SENSORTYPE._serialized_end=415
  _GTSHAPETYPE._serialized_start=417
  _GTSHAPETYPE._serialized_end=516
  _GTOBSTACLEOBJTYPE._serialized_start=519
  _GTOBSTACLEOBJTYPE._serialized_end=1023
  _DATAQUALIFIER._serialized_start=1025
  _DATAQUALIFIER._serialized_end=1121
  _FAULTTYPE._serialized_start=1123
  _FAULTTYPE._serialized_end=1164
# @@protoc_insertion_point(module_scope)
