# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/common/enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17morai/common/enum.proto\x12\rmorai_sim_api*F\n\nStatusCode\x12\x1f\n\x1bSTATUS_CODE_UNKNOWN_FAILURE\x10\x00\x12\x17\n\x13STATUS_CODE_SUCCESS\x10\x01*\x95\x01\n\nObjectType\x12\x1b\n\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13OBJECT_TYPE_VEHICLE\x10\x01\x12\x1a\n\x16OBJECT_TYPE_PEDESTRIAN\x10\x02\x12\x18\n\x14OBJECT_TYPE_OBSTACLE\x10\x03\x12\x1b\n\x17OBJECT_TYPE_SPAWN_POINT\x10\x04\x42&H\x01\xaa\x02!CoreLib.Grpc.Protobuf.MoraiSimAPIb\x06proto3')

_STATUSCODE = DESCRIPTOR.enum_types_by_name['StatusCode']
StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
_OBJECTTYPE = DESCRIPTOR.enum_types_by_name['ObjectType']
ObjectType = enum_type_wrapper.EnumTypeWrapper(_OBJECTTYPE)
STATUS_CODE_UNKNOWN_FAILURE = 0
STATUS_CODE_SUCCESS = 1
OBJECT_TYPE_UNSPECIFIED = 0
OBJECT_TYPE_VEHICLE = 1
OBJECT_TYPE_PEDESTRIAN = 2
OBJECT_TYPE_OBSTACLE = 3
OBJECT_TYPE_SPAWN_POINT = 4


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002!CoreLib.Grpc.Protobuf.MoraiSimAPI'
  _STATUSCODE._serialized_start=42
  _STATUSCODE._serialized_end=112
  _OBJECTTYPE._serialized_start=115
  _OBJECTTYPE._serialized_end=264
# @@protoc_insertion_point(module_scope)
