# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/common/object_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import object_identifier_pb2 as morai_dot_common_dot_object__identifier__pb2
from morai.common import enum_pb2 as morai_dot_common_dot_enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emorai/common/object_info.proto\x12\rmorai_sim_api\x1a$morai/common/object_identifier.proto\x1a\x17morai/common/enum.proto\"}\n\nObjectInfo\x12+\n\x02id\x18\x01 \x01(\x0b\x32\x1f.morai_sim_api.ObjectIdentifier\x12.\n\x0bobject_type\x18\x02 \x01(\x0e\x32\x19.morai_sim_api.ObjectType\x12\x12\n\nclient_key\x18\x03 \x01(\t\"8\n\x0bObjectInfos\x12)\n\x06values\x18\x01 \x03(\x0b\x32\x19.morai_sim_api.ObjectInfoB&H\x01\xaa\x02!CoreLib.Grpc.Protobuf.MoraiSimAPIb\x06proto3')



_OBJECTINFO = DESCRIPTOR.message_types_by_name['ObjectInfo']
_OBJECTINFOS = DESCRIPTOR.message_types_by_name['ObjectInfos']
ObjectInfo = _reflection.GeneratedProtocolMessageType('ObjectInfo', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTINFO,
  '__module__' : 'morai.common.object_info_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.ObjectInfo)
  })
_sym_db.RegisterMessage(ObjectInfo)

ObjectInfos = _reflection.GeneratedProtocolMessageType('ObjectInfos', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTINFOS,
  '__module__' : 'morai.common.object_info_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.ObjectInfos)
  })
_sym_db.RegisterMessage(ObjectInfos)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002!CoreLib.Grpc.Protobuf.MoraiSimAPI'
  _OBJECTINFO._serialized_start=112
  _OBJECTINFO._serialized_end=237
  _OBJECTINFOS._serialized_start=239
  _OBJECTINFOS._serialized_end=295
# @@protoc_insertion_point(module_scope)
