# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/common/object_identifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$morai/common/object_identifier.proto\x12\rmorai_sim_api\"!\n\x10ObjectIdentifier\x12\r\n\x05value\x18\x01 \x01(\tB&H\x01\xaa\x02!CoreLib.Grpc.Protobuf.MoraiSimAPIb\x06proto3')



_OBJECTIDENTIFIER = DESCRIPTOR.message_types_by_name['ObjectIdentifier']
ObjectIdentifier = _reflection.GeneratedProtocolMessageType('ObjectIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTIDENTIFIER,
  '__module__' : 'morai.common.object_identifier_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.ObjectIdentifier)
  })
_sym_db.RegisterMessage(ObjectIdentifier)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002!CoreLib.Grpc.Protobuf.MoraiSimAPI'
  _OBJECTIDENTIFIER._serialized_start=55
  _OBJECTIDENTIFIER._serialized_end=88
# @@protoc_insertion_point(module_scope)
