# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/common/resource_identifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&morai/common/resource_identifier.proto\x12\rmorai_sim_api\"#\n\x12ResourceIdentifier\x12\r\n\x05value\x18\x01 \x01(\tB&H\x01\xaa\x02!CoreLib.Grpc.Protobuf.MoraiSimAPIb\x06proto3')



_RESOURCEIDENTIFIER = DESCRIPTOR.message_types_by_name['ResourceIdentifier']
ResourceIdentifier = _reflection.GeneratedProtocolMessageType('ResourceIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEIDENTIFIER,
  '__module__' : 'morai.common.resource_identifier_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.ResourceIdentifier)
  })
_sym_db.RegisterMessage(ResourceIdentifier)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002!CoreLib.Grpc.Protobuf.MoraiSimAPI'
  _RESOURCEIDENTIFIER._serialized_start=57
  _RESOURCEIDENTIFIER._serialized_end=92
# @@protoc_insertion_point(module_scope)
