# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/common/type.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17morai/common/type.proto\x12\rmorai_sim_api\"\x07\n\x05\x45mpty\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"_\n\tTransform\x12(\n\x08location\x18\x01 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12(\n\x08rotation\x18\x02 \x01(\x0b\x32\x16.morai_sim_api.Vector3\"\x89\x01\n\x0b\x42oundingBox\x12&\n\x06\x65xtent\x18\x01 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12(\n\x08location\x18\x02 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12(\n\x08rotation\x18\x03 \x01(\x0b\x32\x16.morai_sim_api.Vector3\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1b\n\nInt32Value\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1b\n\tInt32List\x12\x0e\n\x06values\x18\x01 \x03(\x05\"\x1b\n\nInt64Value\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1c\n\x0bUint32Value\x12\r\n\x05value\x18\x01 \x01(\r\"\x1c\n\x0bUint64Value\x12\r\n\x05value\x18\x01 \x01(\x04\"\x1b\n\nFloatValue\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1c\n\x0b\x44oubleValue\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1a\n\tBoolValue\x12\r\n\x05value\x18\x01 \x01(\x08\"7\n\tUintColor\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\x12\t\n\x01\x61\x18\x04 \x01(\rB&H\x01\xaa\x02!CoreLib.Grpc.Protobuf.MoraiSimAPIb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_POINT = DESCRIPTOR.message_types_by_name['Point']
_VECTOR3 = DESCRIPTOR.message_types_by_name['Vector3']
_TRANSFORM = DESCRIPTOR.message_types_by_name['Transform']
_BOUNDINGBOX = DESCRIPTOR.message_types_by_name['BoundingBox']
_STRINGVALUE = DESCRIPTOR.message_types_by_name['StringValue']
_STRINGLIST = DESCRIPTOR.message_types_by_name['StringList']
_INT32VALUE = DESCRIPTOR.message_types_by_name['Int32Value']
_INT32LIST = DESCRIPTOR.message_types_by_name['Int32List']
_INT64VALUE = DESCRIPTOR.message_types_by_name['Int64Value']
_UINT32VALUE = DESCRIPTOR.message_types_by_name['Uint32Value']
_UINT64VALUE = DESCRIPTOR.message_types_by_name['Uint64Value']
_FLOATVALUE = DESCRIPTOR.message_types_by_name['FloatValue']
_DOUBLEVALUE = DESCRIPTOR.message_types_by_name['DoubleValue']
_BOOLVALUE = DESCRIPTOR.message_types_by_name['BoolValue']
_UINTCOLOR = DESCRIPTOR.message_types_by_name['UintColor']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Empty)
  })
_sym_db.RegisterMessage(Empty)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Point)
  })
_sym_db.RegisterMessage(Point)

Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Vector3)
  })
_sym_db.RegisterMessage(Vector3)

Transform = _reflection.GeneratedProtocolMessageType('Transform', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORM,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Transform)
  })
_sym_db.RegisterMessage(Transform)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDINGBOX,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.BoundingBox)
  })
_sym_db.RegisterMessage(BoundingBox)

StringValue = _reflection.GeneratedProtocolMessageType('StringValue', (_message.Message,), {
  'DESCRIPTOR' : _STRINGVALUE,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.StringValue)
  })
_sym_db.RegisterMessage(StringValue)

StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLIST,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.StringList)
  })
_sym_db.RegisterMessage(StringList)

Int32Value = _reflection.GeneratedProtocolMessageType('Int32Value', (_message.Message,), {
  'DESCRIPTOR' : _INT32VALUE,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Int32Value)
  })
_sym_db.RegisterMessage(Int32Value)

Int32List = _reflection.GeneratedProtocolMessageType('Int32List', (_message.Message,), {
  'DESCRIPTOR' : _INT32LIST,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Int32List)
  })
_sym_db.RegisterMessage(Int32List)

Int64Value = _reflection.GeneratedProtocolMessageType('Int64Value', (_message.Message,), {
  'DESCRIPTOR' : _INT64VALUE,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Int64Value)
  })
_sym_db.RegisterMessage(Int64Value)

Uint32Value = _reflection.GeneratedProtocolMessageType('Uint32Value', (_message.Message,), {
  'DESCRIPTOR' : _UINT32VALUE,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Uint32Value)
  })
_sym_db.RegisterMessage(Uint32Value)

Uint64Value = _reflection.GeneratedProtocolMessageType('Uint64Value', (_message.Message,), {
  'DESCRIPTOR' : _UINT64VALUE,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.Uint64Value)
  })
_sym_db.RegisterMessage(Uint64Value)

FloatValue = _reflection.GeneratedProtocolMessageType('FloatValue', (_message.Message,), {
  'DESCRIPTOR' : _FLOATVALUE,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.FloatValue)
  })
_sym_db.RegisterMessage(FloatValue)

DoubleValue = _reflection.GeneratedProtocolMessageType('DoubleValue', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEVALUE,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.DoubleValue)
  })
_sym_db.RegisterMessage(DoubleValue)

BoolValue = _reflection.GeneratedProtocolMessageType('BoolValue', (_message.Message,), {
  'DESCRIPTOR' : _BOOLVALUE,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.BoolValue)
  })
_sym_db.RegisterMessage(BoolValue)

UintColor = _reflection.GeneratedProtocolMessageType('UintColor', (_message.Message,), {
  'DESCRIPTOR' : _UINTCOLOR,
  '__module__' : 'morai.common.type_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.UintColor)
  })
_sym_db.RegisterMessage(UintColor)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002!CoreLib.Grpc.Protobuf.MoraiSimAPI'
  _EMPTY._serialized_start=42
  _EMPTY._serialized_end=49
  _POINT._serialized_start=51
  _POINT._serialized_end=91
  _VECTOR3._serialized_start=93
  _VECTOR3._serialized_end=135
  _TRANSFORM._serialized_start=137
  _TRANSFORM._serialized_end=232
  _BOUNDINGBOX._serialized_start=235
  _BOUNDINGBOX._serialized_end=372
  _STRINGVALUE._serialized_start=374
  _STRINGVALUE._serialized_end=402
  _STRINGLIST._serialized_start=404
  _STRINGLIST._serialized_end=432
  _INT32VALUE._serialized_start=434
  _INT32VALUE._serialized_end=461
  _INT32LIST._serialized_start=463
  _INT32LIST._serialized_end=490
  _INT64VALUE._serialized_start=492
  _INT64VALUE._serialized_end=519
  _UINT32VALUE._serialized_start=521
  _UINT32VALUE._serialized_end=549
  _UINT64VALUE._serialized_start=551
  _UINT64VALUE._serialized_end=579
  _FLOATVALUE._serialized_start=581
  _FLOATVALUE._serialized_end=608
  _DOUBLEVALUE._serialized_start=610
  _DOUBLEVALUE._serialized_end=638
  _BOOLVALUE._serialized_start=640
  _BOOLVALUE._serialized_end=666
  _UINTCOLOR._serialized_start=668
  _UINTCOLOR._serialized_end=723
# @@protoc_insertion_point(module_scope)
