# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/actor/actor_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2
from morai.actor import actor_enum_pb2 as morai_dot_actor_dot_actor__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmorai/actor/actor_control.proto\x12\x13morai_sim_api.actor\x1a\x17morai/common/type.proto\x1a\x1emorai/common/object_info.proto\x1a\x1cmorai/actor/actor_enum.proto\"\xdf\x01\n\x0eVehicleCtrlCmd\x12-\n\nactor_info\x18\x01 \x01(\x0b\x32\x19.morai_sim_api.ObjectInfo\x12\x37\n\rlong_cmd_type\x18\x02 \x01(\x0e\x32 .morai_sim_api.actor.LongCmdType\x12\x10\n\x08throttle\x18\x03 \x01(\x01\x12\r\n\x05\x62rake\x18\x04 \x01(\x01\x12\r\n\x05steer\x18\x05 \x01(\x01\x12\x10\n\x08velocity\x18\x06 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x07 \x01(\x01\x12\r\n\x05\x66rame\x18\x08 \x01(\r\"|\n\x11PedestrianCtrlCmd\x12-\n\nactor_info\x18\x01 \x01(\x0b\x32\x19.morai_sim_api.ObjectInfo\x12)\n\tdirection\x18\x02 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12\r\n\x05speed\x18\x03 \x01(\x02\"\xd3\x01\n\x0fObstacleCtrlCmd\x12-\n\nactor_info\x18\x01 \x01(\x0b\x32\x19.morai_sim_api.ObjectInfo\x12\x38\n\x04mode\x18\x02 \x01(\x0e\x32*.morai_sim_api.actor.ObjectControlModeType\x12\r\n\x05\x66rame\x18\x03 \x01(\r\x12\x12\n\nvelocity_x\x18\x04 \x01(\x01\x12\x12\n\nvelocity_y\x18\x05 \x01(\x01\x12\x10\n\x08yaw_rate\x18\x06 \x01(\x01\x12\x0e\n\x06height\x18\x07 \x01(\x01\x42,H\x01\xaa\x02\'CoreLib.Grpc.Protobuf.MoraiSimAPI.Actorb\x06proto3')



_VEHICLECTRLCMD = DESCRIPTOR.message_types_by_name['VehicleCtrlCmd']
_PEDESTRIANCTRLCMD = DESCRIPTOR.message_types_by_name['PedestrianCtrlCmd']
_OBSTACLECTRLCMD = DESCRIPTOR.message_types_by_name['ObstacleCtrlCmd']
VehicleCtrlCmd = _reflection.GeneratedProtocolMessageType('VehicleCtrlCmd', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLECTRLCMD,
  '__module__' : 'morai.actor.actor_control_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.VehicleCtrlCmd)
  })
_sym_db.RegisterMessage(VehicleCtrlCmd)

PedestrianCtrlCmd = _reflection.GeneratedProtocolMessageType('PedestrianCtrlCmd', (_message.Message,), {
  'DESCRIPTOR' : _PEDESTRIANCTRLCMD,
  '__module__' : 'morai.actor.actor_control_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.PedestrianCtrlCmd)
  })
_sym_db.RegisterMessage(PedestrianCtrlCmd)

ObstacleCtrlCmd = _reflection.GeneratedProtocolMessageType('ObstacleCtrlCmd', (_message.Message,), {
  'DESCRIPTOR' : _OBSTACLECTRLCMD,
  '__module__' : 'morai.actor.actor_control_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.ObstacleCtrlCmd)
  })
_sym_db.RegisterMessage(ObstacleCtrlCmd)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002\'CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor'
  _VEHICLECTRLCMD._serialized_start=144
  _VEHICLECTRLCMD._serialized_end=367
  _PEDESTRIANCTRLCMD._serialized_start=369
  _PEDESTRIANCTRLCMD._serialized_end=493
  _OBSTACLECTRLCMD._serialized_start=496
  _OBSTACLECTRLCMD._serialized_end=707
# @@protoc_insertion_point(module_scope)
