# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/actor/actor_network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.actor import actor_enum_pb2 as morai_dot_actor_dot_actor__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmorai/actor/actor_network.proto\x12\x13morai_sim_api.actor\x1a\x1cmorai/actor/actor_enum.proto\"\x81\x01\n\x10NetworkIpSetting\x12<\n\x0c\x63onnect_type\x18\x01 \x01(\x0e\x32&.morai_sim_api.actor.NetworkConnetType\x12/\n\x05items\x18\x02 \x03(\x0b\x32 .morai_sim_api.actor.NetworkItem\"\x8a\x01\n\x16NetworkProtocolSetting\x12\x37\n\tcomm_type\x18\x01 \x01(\x0e\x32$.morai_sim_api.actor.NetworkCommType\x12\x37\n\x05items\x18\x02 \x03(\x0b\x32(.morai_sim_api.actor.NetworkProtocolItem\"z\n\x13NetworkProtocolItem\x12\x32\n\x08protocol\x18\x01 \x01(\x0e\x32 .morai_sim_api.actor.PUBSUB_TYPE\x12/\n\x05items\x18\x02 \x03(\x0b\x32 .morai_sim_api.actor.NetworkItem\"P\n\x0bNetworkItem\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.morai_sim_api.actor.NetworkItemType\x12\r\n\x05value\x18\x02 \x01(\tB,H\x01\xaa\x02\'CoreLib.Grpc.Protobuf.MoraiSimAPI.Actorb\x06proto3')



_NETWORKIPSETTING = DESCRIPTOR.message_types_by_name['NetworkIpSetting']
_NETWORKPROTOCOLSETTING = DESCRIPTOR.message_types_by_name['NetworkProtocolSetting']
_NETWORKPROTOCOLITEM = DESCRIPTOR.message_types_by_name['NetworkProtocolItem']
_NETWORKITEM = DESCRIPTOR.message_types_by_name['NetworkItem']
NetworkIpSetting = _reflection.GeneratedProtocolMessageType('NetworkIpSetting', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKIPSETTING,
  '__module__' : 'morai.actor.actor_network_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.NetworkIpSetting)
  })
_sym_db.RegisterMessage(NetworkIpSetting)

NetworkProtocolSetting = _reflection.GeneratedProtocolMessageType('NetworkProtocolSetting', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKPROTOCOLSETTING,
  '__module__' : 'morai.actor.actor_network_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.NetworkProtocolSetting)
  })
_sym_db.RegisterMessage(NetworkProtocolSetting)

NetworkProtocolItem = _reflection.GeneratedProtocolMessageType('NetworkProtocolItem', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKPROTOCOLITEM,
  '__module__' : 'morai.actor.actor_network_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.NetworkProtocolItem)
  })
_sym_db.RegisterMessage(NetworkProtocolItem)

NetworkItem = _reflection.GeneratedProtocolMessageType('NetworkItem', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKITEM,
  '__module__' : 'morai.actor.actor_network_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.NetworkItem)
  })
_sym_db.RegisterMessage(NetworkItem)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002\'CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor'
  _NETWORKIPSETTING._serialized_start=87
  _NETWORKIPSETTING._serialized_end=216
  _NETWORKPROTOCOLSETTING._serialized_start=219
  _NETWORKPROTOCOLSETTING._serialized_end=357
  _NETWORKPROTOCOLITEM._serialized_start=359
  _NETWORKPROTOCOLITEM._serialized_end=481
  _NETWORKITEM._serialized_start=483
  _NETWORKITEM._serialized_end=563
# @@protoc_insertion_point(module_scope)
