# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/actor/actor_spawn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmorai/actor/actor_spawn.proto\x12\x13morai_sim_api.actor\x1a\x17morai/common/type.proto\x1a\x1emorai/common/object_info.proto\"\x80\x01\n\x11VehicleSpawnParam\x12\x37\n\nspawn_info\x18\x01 \x01(\x0b\x32#.morai_sim_api.actor.ActorSpawnInfo\x12\x10\n\x08velocity\x18\x02 \x01(\x01\x12\r\n\x05pause\x18\x03 \x01(\x08\x12\x11\n\tmulti_ego\x18\x04 \x01(\x08\"\xdc\x01\n\x14PedestrianSpawnParam\x12\x37\n\nspawn_info\x18\x01 \x01(\x0b\x32#.morai_sim_api.actor.ActorSpawnInfo\x12\x10\n\x08velocity\x18\x02 \x01(\x02\x12\x13\n\x0b\x61\x63tive_dist\x18\x03 \x01(\x02\x12\x11\n\tmove_dist\x18\x04 \x01(\x02\x12\x14\n\x0cstart_action\x18\x05 \x01(\x08\x12;\n\twaypoints\x18\x06 \x01(\x0b\x32(.morai_sim_api.actor.PedestrianWaypoints\"t\n\x12ObstacleSpawnParam\x12\x37\n\nspawn_info\x18\x01 \x01(\x0b\x32#.morai_sim_api.actor.ActorSpawnInfo\x12%\n\x05scale\x18\x02 \x01(\x0b\x32\x16.morai_sim_api.Vector3\"\x97\x02\n\x0e\x41\x63torSpawnInfo\x12-\n\nactor_info\x18\x01 \x01(\x0b\x32\x19.morai_sim_api.ObjectInfo\x12+\n\ttransform\x18\x02 \x01(\x0b\x32\x18.morai_sim_api.Transform\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\r\n\x05label\x18\x04 \x01(\t\x12 \n\x18is_multi_object_one_mode\x18\x05 \x01(\x08\x12\'\n\x05\x63olor\x18\x06 \x01(\x0b\x32\x18.morai_sim_api.UintColor\x12-\n\x0blabel_color\x18\x07 \x01(\x0b\x32\x18.morai_sim_api.UintColor\x12\x0c\n\x04mass\x18\x08 \x01(\x02\"Q\n\x13PedestrianWaypoints\x12:\n\twaypoints\x18\x01 \x03(\x0b\x32\'.morai_sim_api.actor.PedestrianWaypoint\"a\n\x12PedestrianWaypoint\x12(\n\x08waypoint\x18\x01 \x01(\x0b\x32\x16.morai_sim_api.Vector3\x12\x12\n\npause_time\x18\x02 \x01(\x02\x12\r\n\x05speed\x18\x03 \x01(\x02\x42,H\x01\xaa\x02\'CoreLib.Grpc.Protobuf.MoraiSimAPI.Actorb\x06proto3')



_VEHICLESPAWNPARAM = DESCRIPTOR.message_types_by_name['VehicleSpawnParam']
_PEDESTRIANSPAWNPARAM = DESCRIPTOR.message_types_by_name['PedestrianSpawnParam']
_OBSTACLESPAWNPARAM = DESCRIPTOR.message_types_by_name['ObstacleSpawnParam']
_ACTORSPAWNINFO = DESCRIPTOR.message_types_by_name['ActorSpawnInfo']
_PEDESTRIANWAYPOINTS = DESCRIPTOR.message_types_by_name['PedestrianWaypoints']
_PEDESTRIANWAYPOINT = DESCRIPTOR.message_types_by_name['PedestrianWaypoint']
VehicleSpawnParam = _reflection.GeneratedProtocolMessageType('VehicleSpawnParam', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLESPAWNPARAM,
  '__module__' : 'morai.actor.actor_spawn_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.VehicleSpawnParam)
  })
_sym_db.RegisterMessage(VehicleSpawnParam)

PedestrianSpawnParam = _reflection.GeneratedProtocolMessageType('PedestrianSpawnParam', (_message.Message,), {
  'DESCRIPTOR' : _PEDESTRIANSPAWNPARAM,
  '__module__' : 'morai.actor.actor_spawn_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.PedestrianSpawnParam)
  })
_sym_db.RegisterMessage(PedestrianSpawnParam)

ObstacleSpawnParam = _reflection.GeneratedProtocolMessageType('ObstacleSpawnParam', (_message.Message,), {
  'DESCRIPTOR' : _OBSTACLESPAWNPARAM,
  '__module__' : 'morai.actor.actor_spawn_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.ObstacleSpawnParam)
  })
_sym_db.RegisterMessage(ObstacleSpawnParam)

ActorSpawnInfo = _reflection.GeneratedProtocolMessageType('ActorSpawnInfo', (_message.Message,), {
  'DESCRIPTOR' : _ACTORSPAWNINFO,
  '__module__' : 'morai.actor.actor_spawn_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.ActorSpawnInfo)
  })
_sym_db.RegisterMessage(ActorSpawnInfo)

PedestrianWaypoints = _reflection.GeneratedProtocolMessageType('PedestrianWaypoints', (_message.Message,), {
  'DESCRIPTOR' : _PEDESTRIANWAYPOINTS,
  '__module__' : 'morai.actor.actor_spawn_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.PedestrianWaypoints)
  })
_sym_db.RegisterMessage(PedestrianWaypoints)

PedestrianWaypoint = _reflection.GeneratedProtocolMessageType('PedestrianWaypoint', (_message.Message,), {
  'DESCRIPTOR' : _PEDESTRIANWAYPOINT,
  '__module__' : 'morai.actor.actor_spawn_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.actor.PedestrianWaypoint)
  })
_sym_db.RegisterMessage(PedestrianWaypoint)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002\'CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor'
  _VEHICLESPAWNPARAM._serialized_start=112
  _VEHICLESPAWNPARAM._serialized_end=240
  _PEDESTRIANSPAWNPARAM._serialized_start=243
  _PEDESTRIANSPAWNPARAM._serialized_end=463
  _OBSTACLESPAWNPARAM._serialized_start=465
  _OBSTACLESPAWNPARAM._serialized_end=581
  _ACTORSPAWNINFO._serialized_start=584
  _ACTORSPAWNINFO._serialized_end=863
  _PEDESTRIANWAYPOINTS._serialized_start=865
  _PEDESTRIANWAYPOINTS._serialized_end=946
  _PEDESTRIANWAYPOINT._serialized_start=948
  _PEDESTRIANWAYPOINT._serialized_end=1045
# @@protoc_insertion_point(module_scope)
