# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.actor import actor_control_pb2 as morai_dot_actor_dot_actor__control__pb2
from morai.actor import actor_get_pb2 as morai_dot_actor_dot_actor__get__pb2
from morai.actor import actor_network_pb2 as morai_dot_actor_dot_actor__network__pb2
from morai.actor import actor_set_pb2 as morai_dot_actor_dot_actor__set__pb2
from morai.actor import actor_spawn_pb2 as morai_dot_actor_dot_actor__spawn__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2
from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.common import type_pb2 as morai_dot_common_dot_type__pb2


class ActorStub(object):
    """*
    Actor (차량, 보행자, 장애물) 관련 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpawnVehicle = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SpawnVehicle',
                request_serializer=morai_dot_actor_dot_actor__spawn__pb2.VehicleSpawnParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SpawnPedestrian = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SpawnPedestrian',
                request_serializer=morai_dot_actor_dot_actor__spawn__pb2.PedestrianSpawnParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SpawnObstacle = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SpawnObstacle',
                request_serializer=morai_dot_actor_dot_actor__spawn__pb2.ObstacleSpawnParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.DestroyActor = channel.unary_unary(
                '/morai_sim_api.actor.Actor/DestroyActor',
                request_serializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.DestroyAllActors = channel.unary_unary(
                '/morai_sim_api.actor.Actor/DestroyAllActors',
                request_serializer=morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.ControlVehicle = channel.unary_unary(
                '/morai_sim_api.actor.Actor/ControlVehicle',
                request_serializer=morai_dot_actor_dot_actor__control__pb2.VehicleCtrlCmd.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.ControlPedestrian = channel.unary_unary(
                '/morai_sim_api.actor.Actor/ControlPedestrian',
                request_serializer=morai_dot_actor_dot_actor__control__pb2.PedestrianCtrlCmd.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.ControlObstacle = channel.unary_unary(
                '/morai_sim_api.actor.Actor/ControlObstacle',
                request_serializer=morai_dot_actor_dot_actor__control__pb2.ObstacleCtrlCmd.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetActorState = channel.unary_unary(
                '/morai_sim_api.actor.Actor/GetActorState',
                request_serializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
                response_deserializer=morai_dot_actor_dot_actor__get__pb2.ActorState.FromString,
                )
        self.GetAllActorsState = channel.unary_unary(
                '/morai_sim_api.actor.Actor/GetAllActorsState',
                request_serializer=morai_dot_actor_dot_actor__get__pb2.GetAllActorsFilter.SerializeToString,
                response_deserializer=morai_dot_actor_dot_actor__get__pb2.ActorStates.FromString,
                )
        self.GetVehicleSpec = channel.unary_unary(
                '/morai_sim_api.actor.Actor/GetVehicleSpec',
                request_serializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
                response_deserializer=morai_dot_actor_dot_actor__get__pb2.VehicleSpec.FromString,
                )
        self.GetOptionName = channel.unary_unary(
                '/morai_sim_api.actor.Actor/GetOptionName',
                request_serializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.StringValue.FromString,
                )
        self.GetVehicleNetworkSetting = channel.unary_unary(
                '/morai_sim_api.actor.Actor/GetVehicleNetworkSetting',
                request_serializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
                response_deserializer=morai_dot_actor_dot_actor__network__pb2.NetworkProtocolSetting.FromString,
                )
        self.GetVehicleControlMode = channel.unary_unary(
                '/morai_sim_api.actor.Actor/GetVehicleControlMode',
                request_serializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
                response_deserializer=morai_dot_actor_dot_actor__get__pb2.CurVehicleControlMode.FromString,
                )
        self.SetScale = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetScale',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.ActorScale.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetTransform = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetTransform',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.SetTransformParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetObstacleAnimation = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetObstacleAnimation',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.AnimationParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetTrainSignalLight = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetTrainSignalLight',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.TrainSignalLightInfo.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetPause = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetPause',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.EnableActor.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetAI = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetAI',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.EnableActor.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetPhysics = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetPhysics',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.EnableActor.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVelocity = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVelocity',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.SetVelocityParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleLimiter = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleLimiter',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleLimiter.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleDynamicsSteer = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleDynamicsSteer',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsSteer.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleDynamicsSpeedLimit = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleDynamicsSpeedLimit',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsSpeedLimit.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleDynamicsMass = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleDynamicsMass',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsMass.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehiclePathOffset = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehiclePathOffset',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehiclePathOffset.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleDisturbance = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleDisturbance',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleDisturbance.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleFaultInjection = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleFaultInjection',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleFaultInjection.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleRoute = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleRoute',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleRoute.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleDestination = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleDestination',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleDestination.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleEgoCruise = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleEgoCruise',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.EgoCruiseControl.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleNetwork = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleNetwork',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.NetworkConfig.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleSteer = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleSteer',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleSteer.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleControlMode = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleControlMode',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleControlModeParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleGear = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleGear',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleGear.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetVehicleTailLight = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetVehicleTailLight',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.VehicleTailLight.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetPedestrianWaypoint = channel.unary_unary(
                '/morai_sim_api.actor.Actor/SetPedestrianWaypoint',
                request_serializer=morai_dot_actor_dot_actor__set__pb2.PedestrianWaypointInfo.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )


class ActorServicer(object):
    """*
    Actor (차량, 보행자, 장애물) 관련 서비스
    """

    def SpawnVehicle(self, request, context):
        """차량 스폰
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpawnPedestrian(self, request, context):
        """보행자 스폰
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpawnObstacle(self, request, context):
        """장애물 스폰
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyActor(self, request, context):
        """선택한 Actor 제거
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyAllActors(self, request, context):
        """*
        모든 Actor 제거
        Client key를 넣으면 해당 key로 관리하는 actor만,
        비어있는 문자열을 넣으면 모든 actor를 제거한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlVehicle(self, request, context):
        """차량 제어
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlPedestrian(self, request, context):
        """보행자 제어
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlObstacle(self, request, context):
        """오브젝트 제어
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorState(self, request, context):
        """// 모든 Actor의 상태를 주기적으로 스트리밍
        rpc GetActorStateStream(Empty) returns (stream ActorStates);

        특정 Actor의 상태를 수신
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllActorsState(self, request, context):
        """모든 Actor의 상태를 수신
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleSpec(self, request, context):
        """차량 제원
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOptionName(self, request, context):
        """객체의 옵션명 반환
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleNetworkSetting(self, request, context):
        """차량 네트워크 설정 조회 (단, 현재는 ROS 설정만 지원)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleControlMode(self, request, context):
        """차량의 제어 모드 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetScale(self, request, context):
        """Scale 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTransform(self, request, context):
        """Transform 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetObstacleAnimation(self, request, context):
        """Animation On/Off
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrainSignalLight(self, request, context):
        """기차 신호등 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPause(self, request, context):
        """Pause/Resume
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAI(self, request, context):
        """AI On/Off
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPhysics(self, request, context):
        """Physics On/Off
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVelocity(self, request, context):
        """Set Velocity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleLimiter(self, request, context):
        """차량의 Limiter 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleDynamicsSteer(self, request, context):
        """차량의 Dynamics steer 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleDynamicsSpeedLimit(self, request, context):
        """차량의 Dynamics 최대 속도 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleDynamicsMass(self, request, context):
        """차량의 Dynamics mass 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehiclePathOffset(self, request, context):
        """차량의 Path offset 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleDisturbance(self, request, context):
        """차량의 Disturbance 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleFaultInjection(self, request, context):
        """차량의 Fault injection 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleRoute(self, request, context):
        """차량의 Route 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleDestination(self, request, context):
        """차량의 Destination 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleEgoCruise(self, request, context):
        """Ego 차량의 Cruise 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleNetwork(self, request, context):
        """차량의 Network 설정 (단, 현재는 ROS 설정만 지원)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleSteer(self, request, context):
        """차량의 Steer 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleControlMode(self, request, context):
        """차량의 제어 모드 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleGear(self, request, context):
        """차량의 기어 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleTailLight(self, request, context):
        """차량의 후미등 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPedestrianWaypoint(self, request, context):
        """Spawn한 보행자의 이동 경로 설정
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpawnVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnVehicle,
                    request_deserializer=morai_dot_actor_dot_actor__spawn__pb2.VehicleSpawnParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SpawnPedestrian': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnPedestrian,
                    request_deserializer=morai_dot_actor_dot_actor__spawn__pb2.PedestrianSpawnParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SpawnObstacle': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnObstacle,
                    request_deserializer=morai_dot_actor_dot_actor__spawn__pb2.ObstacleSpawnParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'DestroyActor': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyActor,
                    request_deserializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'DestroyAllActors': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyAllActors,
                    request_deserializer=morai_dot_common_dot_type__pb2.StringValue.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'ControlVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlVehicle,
                    request_deserializer=morai_dot_actor_dot_actor__control__pb2.VehicleCtrlCmd.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'ControlPedestrian': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlPedestrian,
                    request_deserializer=morai_dot_actor_dot_actor__control__pb2.PedestrianCtrlCmd.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'ControlObstacle': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlObstacle,
                    request_deserializer=morai_dot_actor_dot_actor__control__pb2.ObstacleCtrlCmd.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetActorState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorState,
                    request_deserializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.FromString,
                    response_serializer=morai_dot_actor_dot_actor__get__pb2.ActorState.SerializeToString,
            ),
            'GetAllActorsState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllActorsState,
                    request_deserializer=morai_dot_actor_dot_actor__get__pb2.GetAllActorsFilter.FromString,
                    response_serializer=morai_dot_actor_dot_actor__get__pb2.ActorStates.SerializeToString,
            ),
            'GetVehicleSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleSpec,
                    request_deserializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.FromString,
                    response_serializer=morai_dot_actor_dot_actor__get__pb2.VehicleSpec.SerializeToString,
            ),
            'GetOptionName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptionName,
                    request_deserializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
            ),
            'GetVehicleNetworkSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleNetworkSetting,
                    request_deserializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.FromString,
                    response_serializer=morai_dot_actor_dot_actor__network__pb2.NetworkProtocolSetting.SerializeToString,
            ),
            'GetVehicleControlMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleControlMode,
                    request_deserializer=morai_dot_common_dot_object__info__pb2.ObjectInfo.FromString,
                    response_serializer=morai_dot_actor_dot_actor__get__pb2.CurVehicleControlMode.SerializeToString,
            ),
            'SetScale': grpc.unary_unary_rpc_method_handler(
                    servicer.SetScale,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.ActorScale.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTransform,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.SetTransformParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetObstacleAnimation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetObstacleAnimation,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.AnimationParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetTrainSignalLight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrainSignalLight,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.TrainSignalLightInfo.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetPause': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPause,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.EnableActor.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetAI': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAI,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.EnableActor.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetPhysics': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPhysics,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.EnableActor.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVelocity,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.SetVelocityParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleLimiter': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleLimiter,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleLimiter.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleDynamicsSteer': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleDynamicsSteer,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsSteer.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleDynamicsSpeedLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleDynamicsSpeedLimit,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsSpeedLimit.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleDynamicsMass': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleDynamicsMass,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsMass.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehiclePathOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehiclePathOffset,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehiclePathOffset.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleDisturbance': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleDisturbance,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleDisturbance.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleFaultInjection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleFaultInjection,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleFaultInjection.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleRoute,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleRoute.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleDestination,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleDestination.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleEgoCruise': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleEgoCruise,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.EgoCruiseControl.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleNetwork,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.NetworkConfig.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleSteer': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleSteer,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleSteer.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleControlMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleControlMode,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleControlModeParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleGear': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleGear,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleGear.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetVehicleTailLight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleTailLight,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.VehicleTailLight.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetPedestrianWaypoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPedestrianWaypoint,
                    request_deserializer=morai_dot_actor_dot_actor__set__pb2.PedestrianWaypointInfo.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.actor.Actor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Actor(object):
    """*
    Actor (차량, 보행자, 장애물) 관련 서비스
    """

    @staticmethod
    def SpawnVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SpawnVehicle',
            morai_dot_actor_dot_actor__spawn__pb2.VehicleSpawnParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SpawnPedestrian(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SpawnPedestrian',
            morai_dot_actor_dot_actor__spawn__pb2.PedestrianSpawnParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SpawnObstacle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SpawnObstacle',
            morai_dot_actor_dot_actor__spawn__pb2.ObstacleSpawnParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/DestroyActor',
            morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyAllActors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/DestroyAllActors',
            morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/ControlVehicle',
            morai_dot_actor_dot_actor__control__pb2.VehicleCtrlCmd.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlPedestrian(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/ControlPedestrian',
            morai_dot_actor_dot_actor__control__pb2.PedestrianCtrlCmd.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlObstacle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/ControlObstacle',
            morai_dot_actor_dot_actor__control__pb2.ObstacleCtrlCmd.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActorState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/GetActorState',
            morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
            morai_dot_actor_dot_actor__get__pb2.ActorState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllActorsState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/GetAllActorsState',
            morai_dot_actor_dot_actor__get__pb2.GetAllActorsFilter.SerializeToString,
            morai_dot_actor_dot_actor__get__pb2.ActorStates.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/GetVehicleSpec',
            morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
            morai_dot_actor_dot_actor__get__pb2.VehicleSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOptionName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/GetOptionName',
            morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
            morai_dot_common_dot_type__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleNetworkSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/GetVehicleNetworkSetting',
            morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
            morai_dot_actor_dot_actor__network__pb2.NetworkProtocolSetting.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleControlMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/GetVehicleControlMode',
            morai_dot_common_dot_object__info__pb2.ObjectInfo.SerializeToString,
            morai_dot_actor_dot_actor__get__pb2.CurVehicleControlMode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetScale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetScale',
            morai_dot_actor_dot_actor__set__pb2.ActorScale.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetTransform',
            morai_dot_actor_dot_actor__set__pb2.SetTransformParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetObstacleAnimation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetObstacleAnimation',
            morai_dot_actor_dot_actor__set__pb2.AnimationParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTrainSignalLight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetTrainSignalLight',
            morai_dot_actor_dot_actor__set__pb2.TrainSignalLightInfo.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetPause',
            morai_dot_actor_dot_actor__set__pb2.EnableActor.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetAI',
            morai_dot_actor_dot_actor__set__pb2.EnableActor.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPhysics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetPhysics',
            morai_dot_actor_dot_actor__set__pb2.EnableActor.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVelocity',
            morai_dot_actor_dot_actor__set__pb2.SetVelocityParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleLimiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleLimiter',
            morai_dot_actor_dot_actor__set__pb2.VehicleLimiter.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleDynamicsSteer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleDynamicsSteer',
            morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsSteer.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleDynamicsSpeedLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleDynamicsSpeedLimit',
            morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsSpeedLimit.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleDynamicsMass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleDynamicsMass',
            morai_dot_actor_dot_actor__set__pb2.VehicleDynamicsMass.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehiclePathOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehiclePathOffset',
            morai_dot_actor_dot_actor__set__pb2.VehiclePathOffset.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleDisturbance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleDisturbance',
            morai_dot_actor_dot_actor__set__pb2.VehicleDisturbance.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleFaultInjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleFaultInjection',
            morai_dot_actor_dot_actor__set__pb2.VehicleFaultInjection.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleRoute',
            morai_dot_actor_dot_actor__set__pb2.VehicleRoute.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleDestination',
            morai_dot_actor_dot_actor__set__pb2.VehicleDestination.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleEgoCruise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleEgoCruise',
            morai_dot_actor_dot_actor__set__pb2.EgoCruiseControl.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleNetwork',
            morai_dot_actor_dot_actor__set__pb2.NetworkConfig.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleSteer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleSteer',
            morai_dot_actor_dot_actor__set__pb2.VehicleSteer.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleControlMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleControlMode',
            morai_dot_actor_dot_actor__set__pb2.VehicleControlModeParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleGear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleGear',
            morai_dot_actor_dot_actor__set__pb2.VehicleGear.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleTailLight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetVehicleTailLight',
            morai_dot_actor_dot_actor__set__pb2.VehicleTailLight.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPedestrianWaypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.actor.Actor/SetPedestrianWaypoint',
            morai_dot_actor_dot_actor__set__pb2.PedestrianWaypointInfo.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
