# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.infrastructure import city_information_pb2 as morai_dot_infrastructure_dot_city__information__pb2


class city_informationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPopulationMovement = channel.unary_unary(
                '/sungsimdang_city_message.city_information/GetPopulationMovement',
                request_serializer=morai_dot_infrastructure_dot_city__information__pb2.RequestParam.SerializeToString,
                response_deserializer=morai_dot_infrastructure_dot_city__information__pb2.PopulationMovement.FromString,
                )
        self.GetWattage = channel.unary_unary(
                '/sungsimdang_city_message.city_information/GetWattage',
                request_serializer=morai_dot_infrastructure_dot_city__information__pb2.RequestParam.SerializeToString,
                response_deserializer=morai_dot_infrastructure_dot_city__information__pb2.Wattage.FromString,
                )


class city_informationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPopulationMovement(self, request, context):
        """request population movement data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWattage(self, request, context):
        """request wattage data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_city_informationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPopulationMovement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPopulationMovement,
                    request_deserializer=morai_dot_infrastructure_dot_city__information__pb2.RequestParam.FromString,
                    response_serializer=morai_dot_infrastructure_dot_city__information__pb2.PopulationMovement.SerializeToString,
            ),
            'GetWattage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWattage,
                    request_deserializer=morai_dot_infrastructure_dot_city__information__pb2.RequestParam.FromString,
                    response_serializer=morai_dot_infrastructure_dot_city__information__pb2.Wattage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sungsimdang_city_message.city_information', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class city_information(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPopulationMovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sungsimdang_city_message.city_information/GetPopulationMovement',
            morai_dot_infrastructure_dot_city__information__pb2.RequestParam.SerializeToString,
            morai_dot_infrastructure_dot_city__information__pb2.PopulationMovement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWattage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sungsimdang_city_message.city_information/GetWattage',
            morai_dot_infrastructure_dot_city__information__pb2.RequestParam.SerializeToString,
            morai_dot_infrastructure_dot_city__information__pb2.Wattage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
