# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/infrastructure/city_information.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+morai/infrastructure/city_information.proto\x12\x18sungsimdang_city_message\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\x0cRequestParam\x12;\n\x0crequest_type\x18\x01 \x01(\x0e\x32%.sungsimdang_city_message.RequestType\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"4\n\x08\x44\x61tetime\x12\x0c\n\x04year\x18\x01 \x01(\r\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\r\"\xd2\x01\n\x12PopulationMovement\x12\x10\n\x08Latitude\x18\x01 \x01(\x01\x12\x11\n\tLongitude\x18\x02 \x01(\x01\x12\x11\n\tcamera_id\x18\x03 \x01(\x02\x12\x13\n\x0b\x63\x61mera_name\x18\x04 \x01(\x02\x12\x0f\n\x07\x64\x65nsity\x18\x05 \x01(\x02\x12\x18\n\x10population_count\x18\x06 \x01(\r\x12\x15\n\rlocation_desc\x18\x07 \x01(\t\x12-\n\ttimestamp\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"o\n\x07Wattage\x12\x34\n\x08\x64\x61tetime\x18\x01 \x01(\x0b\x32\".sungsimdang_city_message.Datetime\x12\x0f\n\x07snsrseq\x18\x02 \x01(\t\x12\x0e\n\x06snsrid\x18\x03 \x01(\t\x12\r\n\x05\x64\x61tas\x18\x04 \x03(\x02*D\n\x0bRequestType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x17\n\x13POPULATION_MOVEMENT\x10\x01\x12\x0b\n\x07WATTAGE\x10\x02\x32\xda\x01\n\x10\x63ity_information\x12m\n\x15GetPopulationMovement\x12&.sungsimdang_city_message.RequestParam\x1a,.sungsimdang_city_message.PopulationMovement\x12W\n\nGetWattage\x12&.sungsimdang_city_message.RequestParam\x1a!.sungsimdang_city_message.WattageB\x02H\x01\x62\x06proto3')

_REQUESTTYPE = DESCRIPTOR.enum_types_by_name['RequestType']
RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
UNSPECIFIED = 0
POPULATION_MOVEMENT = 1
WATTAGE = 2


_REQUESTPARAM = DESCRIPTOR.message_types_by_name['RequestParam']
_DATETIME = DESCRIPTOR.message_types_by_name['Datetime']
_POPULATIONMOVEMENT = DESCRIPTOR.message_types_by_name['PopulationMovement']
_WATTAGE = DESCRIPTOR.message_types_by_name['Wattage']
RequestParam = _reflection.GeneratedProtocolMessageType('RequestParam', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTPARAM,
  '__module__' : 'morai.infrastructure.city_information_pb2'
  # @@protoc_insertion_point(class_scope:sungsimdang_city_message.RequestParam)
  })
_sym_db.RegisterMessage(RequestParam)

Datetime = _reflection.GeneratedProtocolMessageType('Datetime', (_message.Message,), {
  'DESCRIPTOR' : _DATETIME,
  '__module__' : 'morai.infrastructure.city_information_pb2'
  # @@protoc_insertion_point(class_scope:sungsimdang_city_message.Datetime)
  })
_sym_db.RegisterMessage(Datetime)

PopulationMovement = _reflection.GeneratedProtocolMessageType('PopulationMovement', (_message.Message,), {
  'DESCRIPTOR' : _POPULATIONMOVEMENT,
  '__module__' : 'morai.infrastructure.city_information_pb2'
  # @@protoc_insertion_point(class_scope:sungsimdang_city_message.PopulationMovement)
  })
_sym_db.RegisterMessage(PopulationMovement)

Wattage = _reflection.GeneratedProtocolMessageType('Wattage', (_message.Message,), {
  'DESCRIPTOR' : _WATTAGE,
  '__module__' : 'morai.infrastructure.city_information_pb2'
  # @@protoc_insertion_point(class_scope:sungsimdang_city_message.Wattage)
  })
_sym_db.RegisterMessage(Wattage)

_CITY_INFORMATION = DESCRIPTOR.services_by_name['city_information']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _REQUESTTYPE._serialized_start=610
  _REQUESTTYPE._serialized_end=678
  _REQUESTPARAM._serialized_start=106
  _REQUESTPARAM._serialized_end=228
  _DATETIME._serialized_start=230
  _DATETIME._serialized_end=282
  _POPULATIONMOVEMENT._serialized_start=285
  _POPULATIONMOVEMENT._serialized_end=495
  _WATTAGE._serialized_start=497
  _WATTAGE._serialized_end=608
  _CITY_INFORMATION._serialized_start=681
  _CITY_INFORMATION._serialized_end=899
# @@protoc_insertion_point(module_scope)
