# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.common import object_identifier_pb2 as morai_dot_common_dot_object__identifier__pb2
from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.infrastructure import intersection_pb2 as morai_dot_infrastructure_dot_intersection__pb2
from morai.infrastructure import traffic_light_pb2 as morai_dot_infrastructure_dot_traffic__light__pb2


class InfrastructureStub(object):
    """*
    신호등, RSU(Road Side Unit)등 시뮬레이션 인프라의 상태를 조회하고 제어하는 기능
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrafficLightInfo = channel.unary_unary(
                '/morai_sim_api.infrastructure.Infrastructure/GetTrafficLightInfo',
                request_serializer=morai_dot_infrastructure_dot_traffic__light__pb2.GetTrafficLightInfoParam.SerializeToString,
                response_deserializer=morai_dot_infrastructure_dot_traffic__light__pb2.TrafficLightInfo.FromString,
                )
        self.SetTrafficLightState = channel.unary_unary(
                '/morai_sim_api.infrastructure.Infrastructure/SetTrafficLightState',
                request_serializer=morai_dot_infrastructure_dot_traffic__light__pb2.TrafficLightStateParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.GetIntersectionTLInfo = channel.unary_unary(
                '/morai_sim_api.infrastructure.Infrastructure/GetIntersectionTLInfo',
                request_serializer=morai_dot_common_dot_object__identifier__pb2.ObjectIdentifier.SerializeToString,
                response_deserializer=morai_dot_infrastructure_dot_intersection__pb2.IntersectionState.FromString,
                )
        self.SetIntersectionPhase = channel.unary_unary(
                '/morai_sim_api.infrastructure.Infrastructure/SetIntersectionPhase',
                request_serializer=morai_dot_infrastructure_dot_intersection__pb2.IntersectionPhase.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )
        self.SetIntersectionSchedule = channel.unary_unary(
                '/morai_sim_api.infrastructure.Infrastructure/SetIntersectionSchedule',
                request_serializer=morai_dot_infrastructure_dot_intersection__pb2.IntersectionSchedule.SerializeToString,
                response_deserializer=morai_dot_common_dot_result__pb2.Result.FromString,
                )


class InfrastructureServicer(object):
    """*
    신호등, RSU(Road Side Unit)등 시뮬레이션 인프라의 상태를 조회하고 제어하는 기능
    """

    def GetTrafficLightInfo(self, request, context):
        """링크 또는 신호등의 아이디를 통해 신호등 상태 획득
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrafficLightState(self, request, context):
        """신호등의 상태 변경
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntersectionTLInfo(self, request, context):
        """교차로 신호등 상태 획득
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIntersectionPhase(self, request, context):
        """교차로 phase 변경
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIntersectionSchedule(self, request, context):
        """교차로 schedule 변경
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfrastructureServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrafficLightInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrafficLightInfo,
                    request_deserializer=morai_dot_infrastructure_dot_traffic__light__pb2.GetTrafficLightInfoParam.FromString,
                    response_serializer=morai_dot_infrastructure_dot_traffic__light__pb2.TrafficLightInfo.SerializeToString,
            ),
            'SetTrafficLightState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrafficLightState,
                    request_deserializer=morai_dot_infrastructure_dot_traffic__light__pb2.TrafficLightStateParam.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'GetIntersectionTLInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntersectionTLInfo,
                    request_deserializer=morai_dot_common_dot_object__identifier__pb2.ObjectIdentifier.FromString,
                    response_serializer=morai_dot_infrastructure_dot_intersection__pb2.IntersectionState.SerializeToString,
            ),
            'SetIntersectionPhase': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIntersectionPhase,
                    request_deserializer=morai_dot_infrastructure_dot_intersection__pb2.IntersectionPhase.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
            'SetIntersectionSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIntersectionSchedule,
                    request_deserializer=morai_dot_infrastructure_dot_intersection__pb2.IntersectionSchedule.FromString,
                    response_serializer=morai_dot_common_dot_result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.infrastructure.Infrastructure', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Infrastructure(object):
    """*
    신호등, RSU(Road Side Unit)등 시뮬레이션 인프라의 상태를 조회하고 제어하는 기능
    """

    @staticmethod
    def GetTrafficLightInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.infrastructure.Infrastructure/GetTrafficLightInfo',
            morai_dot_infrastructure_dot_traffic__light__pb2.GetTrafficLightInfoParam.SerializeToString,
            morai_dot_infrastructure_dot_traffic__light__pb2.TrafficLightInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTrafficLightState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.infrastructure.Infrastructure/SetTrafficLightState',
            morai_dot_infrastructure_dot_traffic__light__pb2.TrafficLightStateParam.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIntersectionTLInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.infrastructure.Infrastructure/GetIntersectionTLInfo',
            morai_dot_common_dot_object__identifier__pb2.ObjectIdentifier.SerializeToString,
            morai_dot_infrastructure_dot_intersection__pb2.IntersectionState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetIntersectionPhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.infrastructure.Infrastructure/SetIntersectionPhase',
            morai_dot_infrastructure_dot_intersection__pb2.IntersectionPhase.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetIntersectionSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.infrastructure.Infrastructure/SetIntersectionSchedule',
            morai_dot_infrastructure_dot_intersection__pb2.IntersectionSchedule.SerializeToString,
            morai_dot_common_dot_result__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
