# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/infrastructure/infrastructure_enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.morai/infrastructure/infrastructure_enum.proto\x12\x1cmorai_sim_api.infrastructure*\xe5\x03\n\x11TrafficLightColor\x12\x18\n\x14TL_COLOR_UNSPECIFIED\x10\x00\x12\x0e\n\nTL_COLOR_R\x10\x01\x12\x0e\n\nTL_COLOR_Y\x10\x04\x12\x0f\n\x0bTL_COLOR_SG\x10\x10\x12\x0f\n\x0bTL_COLOR_LG\x10 \x12\x0f\n\x0bTL_COLOR_RG\x10@\x12\x11\n\x0cTL_COLOR_UTG\x10\x80\x01\x12\x11\n\x0cTL_COLOR_ULG\x10\x80\x02\x12\x11\n\x0cTL_COLOR_URG\x10\x80\x04\x12\x11\n\x0cTL_COLOR_LLG\x10\x80\x08\x12\x11\n\x0cTL_COLOR_LRG\x10\x80\x10\x12\x15\n\x11TL_COLOR_R_WITH_Y\x10\x05\x12\x15\n\x11TL_COLOR_Y_WITH_G\x10\x14\x12\x19\n\x15TL_COLOR_Y_WITH_GLEFT\x10$\x12\x19\n\x15TL_COLOR_G_WITH_GLEFT\x10\x30\x12\x19\n\x15TL_COLOR_R_WITH_GLEFT\x10!\x12\x14\n\x0fTL_COLOR_LLG_SG\x10\x90\x08\x12\x13\n\x0eTL_COLOR_R_LLG\x10\x81\x08\x12\x15\n\x10TL_COLOR_ULG_URG\x10\x80\x06\x12\x1f\n\x12TL_COLOR_UNDEFINED\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\"\n\x15TL_COLOR_NOT_DETECTED\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01*l\n\x17GetTrafficLightInfoType\x12\x1b\n\x17GET_TL_INFO_UNSPECIFIED\x10\x00\x12\x1a\n\x16GET_TL_INFO_BY_LINK_ID\x10\x01\x12\x18\n\x14GET_TL_INFO_BY_TL_ID\x10\x02\x42\x35H\x01\xaa\x02\x30\x43oreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructureb\x06proto3')

_TRAFFICLIGHTCOLOR = DESCRIPTOR.enum_types_by_name['TrafficLightColor']
TrafficLightColor = enum_type_wrapper.EnumTypeWrapper(_TRAFFICLIGHTCOLOR)
_GETTRAFFICLIGHTINFOTYPE = DESCRIPTOR.enum_types_by_name['GetTrafficLightInfoType']
GetTrafficLightInfoType = enum_type_wrapper.EnumTypeWrapper(_GETTRAFFICLIGHTINFOTYPE)
TL_COLOR_UNSPECIFIED = 0
TL_COLOR_R = 1
TL_COLOR_Y = 4
TL_COLOR_SG = 16
TL_COLOR_LG = 32
TL_COLOR_RG = 64
TL_COLOR_UTG = 128
TL_COLOR_ULG = 256
TL_COLOR_URG = 512
TL_COLOR_LLG = 1024
TL_COLOR_LRG = 2048
TL_COLOR_R_WITH_Y = 5
TL_COLOR_Y_WITH_G = 20
TL_COLOR_Y_WITH_GLEFT = 36
TL_COLOR_G_WITH_GLEFT = 48
TL_COLOR_R_WITH_GLEFT = 33
TL_COLOR_LLG_SG = 1040
TL_COLOR_R_LLG = 1025
TL_COLOR_ULG_URG = 768
TL_COLOR_UNDEFINED = -1
TL_COLOR_NOT_DETECTED = -2
GET_TL_INFO_UNSPECIFIED = 0
GET_TL_INFO_BY_LINK_ID = 1
GET_TL_INFO_BY_TL_ID = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\0020CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure'
  _TRAFFICLIGHTCOLOR._serialized_start=81
  _TRAFFICLIGHTCOLOR._serialized_end=566
  _GETTRAFFICLIGHTINFOTYPE._serialized_start=568
  _GETTRAFFICLIGHTINFOTYPE._serialized_end=676
# @@protoc_insertion_point(module_scope)
