# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/infrastructure/infrastructure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import result_pb2 as morai_dot_common_dot_result__pb2
from morai.common import object_identifier_pb2 as morai_dot_common_dot_object__identifier__pb2
from morai.infrastructure import traffic_light_pb2 as morai_dot_infrastructure_dot_traffic__light__pb2
from morai.infrastructure import intersection_pb2 as morai_dot_infrastructure_dot_intersection__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)morai/infrastructure/infrastructure.proto\x12\x1cmorai_sim_api.infrastructure\x1a\x19morai/common/result.proto\x1a$morai/common/object_identifier.proto\x1a(morai/infrastructure/traffic_light.proto\x1a\'morai/infrastructure/intersection.proto2\xa5\x04\n\x0eInfrastructure\x12}\n\x13GetTrafficLightInfo\x12\x36.morai_sim_api.infrastructure.GetTrafficLightInfoParam\x1a..morai_sim_api.infrastructure.TrafficLightInfo\x12\x63\n\x14SetTrafficLightState\x12\x34.morai_sim_api.infrastructure.TrafficLightStateParam\x1a\x15.morai_sim_api.Result\x12i\n\x15GetIntersectionTLInfo\x12\x1f.morai_sim_api.ObjectIdentifier\x1a/.morai_sim_api.infrastructure.IntersectionState\x12^\n\x14SetIntersectionPhase\x12/.morai_sim_api.infrastructure.IntersectionPhase\x1a\x15.morai_sim_api.Result\x12\x64\n\x17SetIntersectionSchedule\x12\x32.morai_sim_api.infrastructure.IntersectionSchedule\x1a\x15.morai_sim_api.ResultB5H\x01\xaa\x02\x30\x43oreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructureb\x06proto3')



_INFRASTRUCTURE = DESCRIPTOR.services_by_name['Infrastructure']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\0020CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure'
  _INFRASTRUCTURE._serialized_start=224
  _INFRASTRUCTURE._serialized_end=773
# @@protoc_insertion_point(module_scope)
