# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/infrastructure/intersection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import object_identifier_pb2 as morai_dot_common_dot_object__identifier__pb2
from morai.infrastructure import traffic_light_pb2 as morai_dot_infrastructure_dot_traffic__light__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'morai/infrastructure/intersection.proto\x12\x1cmorai_sim_api.infrastructure\x1a$morai/common/object_identifier.proto\x1a(morai/infrastructure/traffic_light.proto\"O\n\x11IntersectionPhase\x12+\n\x02id\x18\x01 \x01(\x0b\x32\x1f.morai_sim_api.ObjectIdentifier\x12\r\n\x05phase\x18\x02 \x01(\x05\"\xae\x02\n\x14IntersectionSchedule\x12+\n\x02id\x18\x01 \x01(\x0b\x32\x1f.morai_sim_api.ObjectIdentifier\x12K\n\x07vehicle\x18\x02 \x03(\x0b\x32:.morai_sim_api.infrastructure.TrafficLightSchedule.Vehicle\x12I\n\x06yellow\x18\x03 \x03(\x0b\x32\x39.morai_sim_api.infrastructure.TrafficLightSchedule.Yellow\x12Q\n\npedestrian\x18\x04 \x03(\x0b\x32=.morai_sim_api.infrastructure.TrafficLightSchedule.Pedestrian\"j\n\x11IntersectionState\x12\x46\n\x0etraffic_lights\x18\x01 \x03(\x0b\x32..morai_sim_api.infrastructure.TrafficLightInfo\x12\r\n\x05phase\x18\x02 \x01(\x05\x42\x35H\x01\xaa\x02\x30\x43oreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructureb\x06proto3')



_INTERSECTIONPHASE = DESCRIPTOR.message_types_by_name['IntersectionPhase']
_INTERSECTIONSCHEDULE = DESCRIPTOR.message_types_by_name['IntersectionSchedule']
_INTERSECTIONSTATE = DESCRIPTOR.message_types_by_name['IntersectionState']
IntersectionPhase = _reflection.GeneratedProtocolMessageType('IntersectionPhase', (_message.Message,), {
  'DESCRIPTOR' : _INTERSECTIONPHASE,
  '__module__' : 'morai.infrastructure.intersection_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.IntersectionPhase)
  })
_sym_db.RegisterMessage(IntersectionPhase)

IntersectionSchedule = _reflection.GeneratedProtocolMessageType('IntersectionSchedule', (_message.Message,), {
  'DESCRIPTOR' : _INTERSECTIONSCHEDULE,
  '__module__' : 'morai.infrastructure.intersection_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.IntersectionSchedule)
  })
_sym_db.RegisterMessage(IntersectionSchedule)

IntersectionState = _reflection.GeneratedProtocolMessageType('IntersectionState', (_message.Message,), {
  'DESCRIPTOR' : _INTERSECTIONSTATE,
  '__module__' : 'morai.infrastructure.intersection_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.IntersectionState)
  })
_sym_db.RegisterMessage(IntersectionState)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\0020CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure'
  _INTERSECTIONPHASE._serialized_start=153
  _INTERSECTIONPHASE._serialized_end=232
  _INTERSECTIONSCHEDULE._serialized_start=235
  _INTERSECTIONSCHEDULE._serialized_end=537
  _INTERSECTIONSTATE._serialized_start=539
  _INTERSECTIONSTATE._serialized_end=645
# @@protoc_insertion_point(module_scope)
