# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/infrastructure/traffic_light.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import object_identifier_pb2 as morai_dot_common_dot_object__identifier__pb2
from morai.infrastructure import infrastructure_enum_pb2 as morai_dot_infrastructure_dot_infrastructure__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(morai/infrastructure/traffic_light.proto\x12\x1cmorai_sim_api.infrastructure\x1a$morai/common/object_identifier.proto\x1a.morai/infrastructure/infrastructure_enum.proto\"n\n\x18GetTrafficLightInfoParam\x12\x43\n\x04type\x18\x01 \x01(\x0e\x32\x35.morai_sim_api.infrastructure.GetTrafficLightInfoType\x12\r\n\x05value\x18\x02 \x01(\t\"\x7f\n\x10TrafficLightInfo\x12+\n\x02id\x18\x02 \x01(\x0b\x32\x1f.morai_sim_api.ObjectIdentifier\x12>\n\x05\x63olor\x18\x03 \x01(\x0e\x32/.morai_sim_api.infrastructure.TrafficLightColor\"X\n\x14TrafficLightInfoList\x12@\n\x08res_list\x18\x01 \x03(\x0b\x32..morai_sim_api.infrastructure.TrafficLightInfo\"\x7f\n\x16TrafficLightStateParam\x12<\n\x04info\x18\x01 \x01(\x0b\x32..morai_sim_api.infrastructure.TrafficLightInfo\x12\x12\n\nis_impulse\x18\x02 \x01(\x08\x12\x13\n\x0bset_sibling\x18\x03 \x01(\x08\"\xf1\x01\n\x14TrafficLightSchedule\x1a\x39\n\x07Vehicle\x12\x10\n\x08\x64uration\x18\x01 \x01(\x05\x12\x1c\n\x14str_light_color_list\x18\x02 \x03(\t\x1a\x81\x01\n\nPedestrian\x12\x14\n\x0ctl_state_idx\x18\x01 \x01(\x05\x12\x15\n\rsynced_tl_idx\x18\x02 \x01(\x05\x12\x12\n\nbefore_sec\x18\x03 \x01(\x05\x12\x17\n\x0fgreen_light_sec\x18\x04 \x01(\x05\x12\x19\n\x11\x66licker_light_sec\x18\x05 \x01(\x05\x1a\x1a\n\x06Yellow\x12\x10\n\x08\x64uration\x18\x01 \x01(\x05\x42\x35H\x01\xaa\x02\x30\x43oreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructureb\x06proto3')



_GETTRAFFICLIGHTINFOPARAM = DESCRIPTOR.message_types_by_name['GetTrafficLightInfoParam']
_TRAFFICLIGHTINFO = DESCRIPTOR.message_types_by_name['TrafficLightInfo']
_TRAFFICLIGHTINFOLIST = DESCRIPTOR.message_types_by_name['TrafficLightInfoList']
_TRAFFICLIGHTSTATEPARAM = DESCRIPTOR.message_types_by_name['TrafficLightStateParam']
_TRAFFICLIGHTSCHEDULE = DESCRIPTOR.message_types_by_name['TrafficLightSchedule']
_TRAFFICLIGHTSCHEDULE_VEHICLE = _TRAFFICLIGHTSCHEDULE.nested_types_by_name['Vehicle']
_TRAFFICLIGHTSCHEDULE_PEDESTRIAN = _TRAFFICLIGHTSCHEDULE.nested_types_by_name['Pedestrian']
_TRAFFICLIGHTSCHEDULE_YELLOW = _TRAFFICLIGHTSCHEDULE.nested_types_by_name['Yellow']
GetTrafficLightInfoParam = _reflection.GeneratedProtocolMessageType('GetTrafficLightInfoParam', (_message.Message,), {
  'DESCRIPTOR' : _GETTRAFFICLIGHTINFOPARAM,
  '__module__' : 'morai.infrastructure.traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.GetTrafficLightInfoParam)
  })
_sym_db.RegisterMessage(GetTrafficLightInfoParam)

TrafficLightInfo = _reflection.GeneratedProtocolMessageType('TrafficLightInfo', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICLIGHTINFO,
  '__module__' : 'morai.infrastructure.traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.TrafficLightInfo)
  })
_sym_db.RegisterMessage(TrafficLightInfo)

TrafficLightInfoList = _reflection.GeneratedProtocolMessageType('TrafficLightInfoList', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICLIGHTINFOLIST,
  '__module__' : 'morai.infrastructure.traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.TrafficLightInfoList)
  })
_sym_db.RegisterMessage(TrafficLightInfoList)

TrafficLightStateParam = _reflection.GeneratedProtocolMessageType('TrafficLightStateParam', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICLIGHTSTATEPARAM,
  '__module__' : 'morai.infrastructure.traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.TrafficLightStateParam)
  })
_sym_db.RegisterMessage(TrafficLightStateParam)

TrafficLightSchedule = _reflection.GeneratedProtocolMessageType('TrafficLightSchedule', (_message.Message,), {

  'Vehicle' : _reflection.GeneratedProtocolMessageType('Vehicle', (_message.Message,), {
    'DESCRIPTOR' : _TRAFFICLIGHTSCHEDULE_VEHICLE,
    '__module__' : 'morai.infrastructure.traffic_light_pb2'
    # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.TrafficLightSchedule.Vehicle)
    })
  ,

  'Pedestrian' : _reflection.GeneratedProtocolMessageType('Pedestrian', (_message.Message,), {
    'DESCRIPTOR' : _TRAFFICLIGHTSCHEDULE_PEDESTRIAN,
    '__module__' : 'morai.infrastructure.traffic_light_pb2'
    # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.TrafficLightSchedule.Pedestrian)
    })
  ,

  'Yellow' : _reflection.GeneratedProtocolMessageType('Yellow', (_message.Message,), {
    'DESCRIPTOR' : _TRAFFICLIGHTSCHEDULE_YELLOW,
    '__module__' : 'morai.infrastructure.traffic_light_pb2'
    # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.TrafficLightSchedule.Yellow)
    })
  ,
  'DESCRIPTOR' : _TRAFFICLIGHTSCHEDULE,
  '__module__' : 'morai.infrastructure.traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.infrastructure.TrafficLightSchedule)
  })
_sym_db.RegisterMessage(TrafficLightSchedule)
_sym_db.RegisterMessage(TrafficLightSchedule.Vehicle)
_sym_db.RegisterMessage(TrafficLightSchedule.Pedestrian)
_sym_db.RegisterMessage(TrafficLightSchedule.Yellow)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\0020CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure'
  _GETTRAFFICLIGHTINFOPARAM._serialized_start=160
  _GETTRAFFICLIGHTINFOPARAM._serialized_end=270
  _TRAFFICLIGHTINFO._serialized_start=272
  _TRAFFICLIGHTINFO._serialized_end=399
  _TRAFFICLIGHTINFOLIST._serialized_start=401
  _TRAFFICLIGHTINFOLIST._serialized_end=489
  _TRAFFICLIGHTSTATEPARAM._serialized_start=491
  _TRAFFICLIGHTSTATEPARAM._serialized_end=618
  _TRAFFICLIGHTSCHEDULE._serialized_start=621
  _TRAFFICLIGHTSCHEDULE._serialized_end=862
  _TRAFFICLIGHTSCHEDULE_VEHICLE._serialized_start=645
  _TRAFFICLIGHTSCHEDULE_VEHICLE._serialized_end=702
  _TRAFFICLIGHTSCHEDULE_PEDESTRIAN._serialized_start=705
  _TRAFFICLIGHTSCHEDULE_PEDESTRIAN._serialized_end=834
  _TRAFFICLIGHTSCHEDULE_YELLOW._serialized_start=836
  _TRAFFICLIGHTSCHEDULE_YELLOW._serialized_end=862
# @@protoc_insertion_point(module_scope)
