# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/map/get_neighbor_link_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import resource_identifier_pb2 as morai_dot_common_dot_resource__identifier__pb2
from morai.map import map_enum_pb2 as morai_dot_map_dot_map__enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'morai/map/get_neighbor_link_param.proto\x12\x11morai_sim_api.map\x1a&morai/common/resource_identifier.proto\x1a\x18morai/map/map_enum.proto\"\x84\x01\n\x14GetNeighborLinkParam\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.morai_sim_api.map.NeighborLinkType\x12\x39\n\x0etarget_link_id\x18\x02 \x01(\x0b\x32!.morai_sim_api.ResourceIdentifierB*H\x01\xaa\x02%CoreLib.Grpc.Protobuf.MoraiSimAPI.Mapb\x06proto3')



_GETNEIGHBORLINKPARAM = DESCRIPTOR.message_types_by_name['GetNeighborLinkParam']
GetNeighborLinkParam = _reflection.GeneratedProtocolMessageType('GetNeighborLinkParam', (_message.Message,), {
  'DESCRIPTOR' : _GETNEIGHBORLINKPARAM,
  '__module__' : 'morai.map.get_neighbor_link_param_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.map.GetNeighborLinkParam)
  })
_sym_db.RegisterMessage(GetNeighborLinkParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002%CoreLib.Grpc.Protobuf.MoraiSimAPI.Map'
  _GETNEIGHBORLINKPARAM._serialized_start=129
  _GETNEIGHBORLINKPARAM._serialized_end=261
# @@protoc_insertion_point(module_scope)
