# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/map/link_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import resource_identifier_pb2 as morai_dot_common_dot_resource__identifier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19morai/map/link_info.proto\x12\x11morai_sim_api.map\x1a&morai/common/resource_identifier.proto\"O\n\x08LinkInfo\x12-\n\x02id\x18\x01 \x01(\x0b\x32!.morai_sim_api.ResourceIdentifier\x12\x14\n\x0cwaypoint_idx\x18\x02 \x01(\x05\x42*H\x01\xaa\x02%CoreLib.Grpc.Protobuf.MoraiSimAPI.Mapb\x06proto3')



_LINKINFO = DESCRIPTOR.message_types_by_name['LinkInfo']
LinkInfo = _reflection.GeneratedProtocolMessageType('LinkInfo', (_message.Message,), {
  'DESCRIPTOR' : _LINKINFO,
  '__module__' : 'morai.map.link_info_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.map.LinkInfo)
  })
_sym_db.RegisterMessage(LinkInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002%CoreLib.Grpc.Protobuf.MoraiSimAPI.Map'
  _LINKINFO._serialized_start=88
  _LINKINFO._serialized_end=167
# @@protoc_insertion_point(module_scope)
