# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/map/map_enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18morai/map/map_enum.proto\x12\x11morai_sim_api.map*\xa4\x01\n\x10NeighborLinkType\x12!\n\x1dNEIGHBORLINK_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16NEIGHBORLINK_TYPE_LEFT\x10\x01\x12\x1b\n\x17NEIGHBORLINK_TYPE_RIGHT\x10\x02\x12\x1a\n\x16NEIGHBORLINK_TYPE_FROM\x10\x03\x12\x18\n\x14NEIGHBORLINK_TYPE_TO\x10\x04\x42*H\x01\xaa\x02%CoreLib.Grpc.Protobuf.MoraiSimAPI.Mapb\x06proto3')

_NEIGHBORLINKTYPE = DESCRIPTOR.enum_types_by_name['NeighborLinkType']
NeighborLinkType = enum_type_wrapper.EnumTypeWrapper(_NEIGHBORLINKTYPE)
NEIGHBORLINK_TYPE_UNSPECIFIED = 0
NEIGHBORLINK_TYPE_LEFT = 1
NEIGHBORLINK_TYPE_RIGHT = 2
NEIGHBORLINK_TYPE_FROM = 3
NEIGHBORLINK_TYPE_TO = 4


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002%CoreLib.Grpc.Protobuf.MoraiSimAPI.Map'
  _NEIGHBORLINKTYPE._serialized_start=48
  _NEIGHBORLINKTYPE._serialized_end=212
# @@protoc_insertion_point(module_scope)
