# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/map/map.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2
from morai.map import get_neighbor_link_param_pb2 as morai_dot_map_dot_get__neighbor__link__param__pb2
from morai.map import mgeo_data_pb2 as morai_dot_map_dot_mgeo__data__pb2
from morai.map import link_info_pb2 as morai_dot_map_dot_link__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13morai/map/map.proto\x12\x11morai_sim_api.map\x1a\x17morai/common/type.proto\x1a\x1emorai/common/object_info.proto\x1a\'morai/map/get_neighbor_link_param.proto\x1a\x19morai/map/mgeo_data.proto\x1a\x19morai/map/link_info.proto2\xf4\x01\n\x03Map\x12\x44\n\x07GetMGeo\x12\x1a.morai_sim_api.StringValue\x1a\x1b.morai_sim_api.map.MGeoData\"\x00\x12W\n\x0fGetNeighborLink\x12\'.morai_sim_api.map.GetNeighborLinkParam\x1a\x19.morai_sim_api.StringList\"\x00\x12N\n\x11GetVehiclesOnLink\x12\x1b.morai_sim_api.map.LinkInfo\x1a\x1a.morai_sim_api.ObjectInfos\"\x00\x42*H\x01\xaa\x02%CoreLib.Grpc.Protobuf.MoraiSimAPI.Mapb\x06proto3')



_MAP = DESCRIPTOR.services_by_name['Map']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002%CoreLib.Grpc.Protobuf.MoraiSimAPI.Map'
  _MAP._serialized_start=195
  _MAP._serialized_end=439
# @@protoc_insertion_point(module_scope)
