# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from morai.common import object_info_pb2 as morai_dot_common_dot_object__info__pb2
from morai.common import type_pb2 as morai_dot_common_dot_type__pb2
from morai.map import get_neighbor_link_param_pb2 as morai_dot_map_dot_get__neighbor__link__param__pb2
from morai.map import link_info_pb2 as morai_dot_map_dot_link__info__pb2
from morai.map import mgeo_data_pb2 as morai_dot_map_dot_mgeo__data__pb2


class MapStub(object):
    """지도 관련 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMGeo = channel.unary_unary(
                '/morai_sim_api.map.Map/GetMGeo',
                request_serializer=morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
                response_deserializer=morai_dot_map_dot_mgeo__data__pb2.MGeoData.FromString,
                )
        self.GetNeighborLink = channel.unary_unary(
                '/morai_sim_api.map.Map/GetNeighborLink',
                request_serializer=morai_dot_map_dot_get__neighbor__link__param__pb2.GetNeighborLinkParam.SerializeToString,
                response_deserializer=morai_dot_common_dot_type__pb2.StringList.FromString,
                )
        self.GetVehiclesOnLink = channel.unary_unary(
                '/morai_sim_api.map.Map/GetVehiclesOnLink',
                request_serializer=morai_dot_map_dot_link__info__pb2.LinkInfo.SerializeToString,
                response_deserializer=morai_dot_common_dot_object__info__pb2.ObjectInfos.FromString,
                )


class MapServicer(object):
    """지도 관련 서비스
    """

    def GetMGeo(self, request, context):
        """*
        MGeo 데이터를 가져옴
        Extra scene map의 경우, "V_EXTRA_SCENE,맵이름" 으로 넣어야 한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighborLink(self, request, context):
        """* 
        주변 링크 정보를 가져옴
        성공하면 링크 아이디, 실패하면 비어있는 문자열 리스트 리턴
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehiclesOnLink(self, request, context):
        """*
        링크에 있는 차량 정보를 가져옴
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMGeo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMGeo,
                    request_deserializer=morai_dot_common_dot_type__pb2.StringValue.FromString,
                    response_serializer=morai_dot_map_dot_mgeo__data__pb2.MGeoData.SerializeToString,
            ),
            'GetNeighborLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighborLink,
                    request_deserializer=morai_dot_map_dot_get__neighbor__link__param__pb2.GetNeighborLinkParam.FromString,
                    response_serializer=morai_dot_common_dot_type__pb2.StringList.SerializeToString,
            ),
            'GetVehiclesOnLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehiclesOnLink,
                    request_deserializer=morai_dot_map_dot_link__info__pb2.LinkInfo.FromString,
                    response_serializer=morai_dot_common_dot_object__info__pb2.ObjectInfos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morai_sim_api.map.Map', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Map(object):
    """지도 관련 서비스
    """

    @staticmethod
    def GetMGeo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.map.Map/GetMGeo',
            morai_dot_common_dot_type__pb2.StringValue.SerializeToString,
            morai_dot_map_dot_mgeo__data__pb2.MGeoData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNeighborLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.map.Map/GetNeighborLink',
            morai_dot_map_dot_get__neighbor__link__param__pb2.GetNeighborLinkParam.SerializeToString,
            morai_dot_common_dot_type__pb2.StringList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehiclesOnLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morai_sim_api.map.Map/GetVehiclesOnLink',
            morai_dot_map_dot_link__info__pb2.LinkInfo.SerializeToString,
            morai_dot_common_dot_object__info__pb2.ObjectInfos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
