# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: morai/map/mgeo_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19morai/map/mgeo_data.proto\x12\x11morai_sim_api.map\":\n\x08MGeoData\x12.\n\x07objects\x18\x01 \x03(\x0b\x32\x1d.morai_sim_api.map.MGeoObject\"7\n\nMGeoObject\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x17\n\x0f\x63ompressed_data\x18\x02 \x01(\tB*H\x01\xaa\x02%CoreLib.Grpc.Protobuf.MoraiSimAPI.Mapb\x06proto3')



_MGEODATA = DESCRIPTOR.message_types_by_name['MGeoData']
_MGEOOBJECT = DESCRIPTOR.message_types_by_name['MGeoObject']
MGeoData = _reflection.GeneratedProtocolMessageType('MGeoData', (_message.Message,), {
  'DESCRIPTOR' : _MGEODATA,
  '__module__' : 'morai.map.mgeo_data_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.map.MGeoData)
  })
_sym_db.RegisterMessage(MGeoData)

MGeoObject = _reflection.GeneratedProtocolMessageType('MGeoObject', (_message.Message,), {
  'DESCRIPTOR' : _MGEOOBJECT,
  '__module__' : 'morai.map.mgeo_data_pb2'
  # @@protoc_insertion_point(class_scope:morai_sim_api.map.MGeoObject)
  })
_sym_db.RegisterMessage(MGeoObject)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001\252\002%CoreLib.Grpc.Protobuf.MoraiSimAPI.Map'
  _MGEODATA._serialized_start=48
  _MGEODATA._serialized_end=106
  _MGEOOBJECT._serialized_start=108
  _MGEOOBJECT._serialized_end=163
# @@protoc_insertion_point(module_scope)
